### ISSUE TITLE
Task: clean up landing page and make sure all content is on it

### ISSUE THREAD

**Issue by nlebovits** [CodeForPhilly/vacant-lots-proj#100]
Check against [the Figma prototype](https://www.figma.com/file/NAFkgq34abW6uJ0R7PW24T/Prototype---Vacant-Properties?type=design&node-id=187%3A12603&mode=design&t=qPDRe59d4iFWJtuc-1) to make sure the landing page has all the content it's supposed to and is styled correctly. Coordinate with @thansidwell if you have questions.

**Comment by nlebovits** [comment]
@JosephAni ready to push your commits?

**Comment by thansidwell** [comment]
This layout is pretty tricky. I spent some time working out how it could be done with CSS grid. I also made it responsive for mobile! https://codepen.io/thansidwell/pen/dyrROeq

I've been trying to figure out an alternative way to do it with CSS flexbox but it's been much harder for me.

**Comment by nlebovits** [comment]
closed by #234
