### ISSUE TITLE
Task: remove searchbar from MapControlBar.tsx

### ISSUE THREAD

**Issue by nlebovits** [CodeForPhilly/vacant-lots-proj#108]
Now that the geocoder search bar has been integrated into the PropertyMap.tsx via react-map-gl, we can remove the search bar from the MapControlBar.tsx component.

**Comment by gramzanali-scottlogic** [comment]
Hi, I've opened a pr that should close this issue here [#115](https://github.com/CodeForPhilly/vacant-lots-proj/pull/115).
