### ISSUE TITLE
Task: add link to atlas to property cards

### ISSUE THREAD

**Issue by nlebovits** [CodeForPhilly/vacant-lots-proj#119]
For the property card for a given property, add a hyperlink to the City's Atlas website. 

My old Python code to do this looked like this (obviously this should be done in JavaScript in the PropertyCard.tsx component):

```{python}
joined_gdf['atlas_url'] = '<a href="https://atlas.phila.gov/' + joined_gdf['address'] + '">Click here</a>'
```

**Comment by Kenny4297** [comment]
Hi @nlebovits, I believe that I can help with this issue. Would you mind assigning me to it?

**Comment by nlebovits** [comment]
Sure! Thanks for your interest in contributing. :)

**Comment by nlebovits** [comment]
@all-contributors please add @Kenny4297 for code!
