### ISSUE TITLE
Task: make website responsive (global)

### ISSUE THREAD

**Issue by nlebovits** [CodeForPhilly/vacant-lots-proj#139]
Currently the website is only optimized for use on a desktop/laptop. Because we anticipate that a large portion of our users will only have access to smartphones, we want to make sure the site is also usable on a smartphone.

**Comment by Moylena** [comment]
There are related tickets to specific updates to make the website responsive

**Comment by thansidwell** [comment]
I'm going to archive this ticket since it's too vague and large and we have more specific tickets to solve this issue.

**Comment by nlebovits** [comment]
stale--addressing ongoing
