### ISSUE TITLE
Revise content for the "Take Action" subpages

### ISSUE THREAD

**Issue by nlebovits** [CodeForPhilly/vacant-lots-proj#152]
Change Take Action" page to have subpages: "Get Access" and "Transform a Property". The "Get Access" subpage will cover the legal/practical aspects of getting property access, and the "Transform a Property" page will contain recommendations for how to actually intervene.

**Comment by nlebovits** [comment]
@all-contributors please add @willonabike for research and UX design

**Comment by willonabike** [comment]
Two Aspects to be implemented:
1. Navigation design: [Tabbed view in FIgma
](https://www.figma.com/proto/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?page-id=187%3A12602&type=design&node-id=1039-6122&viewport=-488%2C-414%2C0.07&t=S1jBRKW3lJNR3EAh-1&scaling=scale-down-width&starting-point-node-id=187%3A12709&hotspot-hints=0&mode=design)

2. Content design - in progress 
Take Action
> Get Access
> Transform a Property

**Comment by willonabike** [comment]
Original task completed by Nissim, adding first pass pages for Get Access and Transform a Property.
