### ISSUE TITLE
Task: Style single property detail on sidebar

### ISSUE THREAD

**Issue by brandonfcohen1** [CodeForPhilly/vacant-lots-proj#156]
## Describe the task
Style `PropertyDetailSection` and `SinglePropertyDetail` per [mockups](https://www.figma.com/file/NAFkgq34abW6uJ0R7PW24T/Prototype---Vacant-Properties?type=design&node-id=352%3A24731&mode=design&t=bECjbtOkcoZ1HTcZ-1).

![image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/2308834/b5aec919-2fe9-4b2c-b8f2-460f296256eb)

## Acceptance Criteria

- [ ] Grid view is properly styled
- [ ] Single property view is properly styled

**Comment by nlebovits** [comment]
Per my convo with @markgoetz in Slack:

1) You can leave out drug crime for the moment. Drug crime is a non-essential feature that we'll add at a later date.
2) L&I violations should be the number from the "open_violations_past_year" column
3) For tax delinquency, if the "total_due" column is NULL, then it is NOT tax delinquent. If "total_due" is NOT NULL, then it IS tax delinquent.

Can you also change "Acquisition Process" to "Access Process" while you're at it? Thanks!

"Relevant Info" was a column I had created in a previous iteration of this dataset. It summarized in text form a bunch of information about the property, e.g., "This property is a [land type] located at [address]. Its estimated market value is [market_value] and it is owned by [owner]. It is located in [zip_code] and is served by [rco] and falls in the [council_district]." It's out of date given the latest redesigns to the site. I will check with the UX team about incorporating it elsewhere.

**Comment by nlebovits** [comment]
Also add:
- Atlas link
- market value

**Comment by markgoetz** [comment]
@nlebovits @thansidwell How's this looking?
![Screenshot 2024-01-16 at 9 13 13 PM](https://github.com/CodeForPhilly/vacant-lots-proj/assets/4121678/4734ba6b-f9d9-48c6-8e92-55e717eeea65)

**Comment by thansidwell** [comment]
@markgoetz I just discussed this with @nlebovits and @willonabike 

It seems odd that the only thing on the right is owner, so...
- The owner data can just be another piece of data in the table. 
- The table can then go full width. 

Hopefully, we can get those changes into the prototype soon for you, but it's pretty simple. Is that possible to fit that into this issue ticket, @markgoetz?

**Comment by markgoetz** [comment]
Yep!  I can take care of that in this same ticket.

**Comment by nlebovits** [comment]
@markgoetz this is looking great! while you're at it, can you add this text at the bottom of the panel?

Remove This Property

If you would like to request that we remove this property from the dashboard, please see our <a href="/request-removal" className="text-primary">Request Removal page</a>.

**Comment by nlebovits** [comment]
nvm, added the text myself!

submission looks great--thank you!!
