### ISSUE TITLE
Add Search Engine Data

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#180]
As a user I should see "Clean & Green Philly" in my browser tab. Right now it says "Clean Green Philly".

* Change the page title in the HTML to be “Clean & Green Philly” https://www.w3schools.com/html/html_page_title.asp  
    * Check that it shows up on the browser tab https://share.cleanshot.com/PBcMXsfQ 
    * Later the search engines will crawl it https://share.cleanshot.com/jM1YSyXV 
 
As a user when I search Google for Clean & Green Philly a helpful clear description should show up. Right now the page content just shows up. 

* Add a meta description to the page. https://www.w3schools.com/tags/tag_meta.asp
    * Make the wording “Reduce the gun violence in Philadelphia by finding vacant properties to clean and green them.

**Comment by 19ewalker** [comment]
I can take this ticket

**Comment by thansidwell** [comment]
@19ewalker I assigned this to you and put it in "In Development." We need to figure out how to allow you to do it yourself. Maybe a permission thing.

**Comment by nlebovits** [comment]
> I can take this ticket

thanks @19ewalker!
