### ISSUE TITLE
Improve the Filter UX

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#182]
As a user, I would expect the filter to work similarly to most filters with pills.

* Right now when you click on the filter all the filter options are selected appearing green. This is technically correct, but doesn’t match how modern filters work which better matches how people think. https://share.cleanshot.com/nN3fGsRS 
* Here’s how modern filters work. If you want all high-priority properties, you click “Filter” and then “High”, and boom you get it. But currently, you have to click “Low” and “Medium” to deselect what you don't want to get all “High” priority ones. Not what people expect. 
* Initially, when a user goes to filter ALL filters should appear NOT selected, but that means we should display everything. All properties should be displayed on the map. https://share.cleanshot.com/mFYxR08t 
* When a user selects an option in the filter, THEN the properties on the map should start to become filtered.

**Comment by nlebovits** [comment]
closed by #217

**Comment by thansidwell** [comment]
This is partially implemented. 

- When you deselect a tag, it goes back to showing nothing. Here's a video explaining the issue. https://share.cleanshot.com/zPTlQQHj
