### ISSUE TITLE
Improve Map Controls

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#189]
As a user I want the map controls to be familiar and similar to what I've experienced in other systems like Google Maps and Apple Maps and don't draw too much attention to themselves. 

* Move map controls bottom right. It’s a more common location in popular apps like Google and Apple maps. https://share.cleanshot.com/bzTmR375 
* Allow the map to be zoomed out farther so you can see all of Philadelphia in one view. https://share.cleanshot.com/qZdGvScS 
* Give all map elements the same margin https://share.cleanshot.com/ZCT3HwWw 
* Remove the rotate map button. If possible disallow rotating. I feel it isn’t really helpful and just distracts. https://share.cleanshot.com/3P1yXgcl 

Here's a link to the prototype. https://www.figma.com/file/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=187%3A12604&mode=design&t=h1fTrSpJsuOpTu9c-1

**Comment by nlebovits** [comment]
closed with #209

@brandonfcohen1 we'll need to update the mapbox vt layers to be visibile out to a zoom level of 10

**Comment by thansidwell** [comment]
@brandonfcohen1 I just going to comment on that issue!

**Comment by thansidwell** [comment]
@nlebovits Small change: Can we make the margin on the controls closer to 24px? Right now it's like like 12px. https://share.cleanshot.com/Pm7KxmFp It matches the spacing used throughout the rest of the website and just generally looks nicer.
