### ISSUE TITLE
Add Font

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#192]
As a user I'd like to see a nice professional distinct font that gives the website character. 

- The font being used in the prototype is HK Grotesk. https://www.fontsquirrel.com/fonts/hk-grotesk
- It's using the weights Regular, Bold and Extrabold. No italics needed for now. 
- I uploaded those into Font Squirrel's Webfont Generator. Here's the downloaded kit files. [webfontkit-20240117-085645.zip](https://github.com/CodeForPhilly/vacant-lots-proj/files/13964088/webfontkit-20240117-085645.zip)
- There are some instructions included that can be helpful. I'm not exactly sure how this should be integrated with NextUI. 

Testing
- Ensure that all the text appears in the new font as it appears in the prototype. https://www.figma.com/file/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=187%3A12709&mode=design&t=lP751bx0VsMi1PSs-1

**Comment by markgoetz** [comment]
Heads up for anyone who tries to take a look at this: the included stylesheet in the ZIP may need to be massaged a bit.  Rather than using the same `font-family` and different weights for normal, bold, and extrabold, the stylesheet uses separate `font-family` values and `normal` weight for all of them.

**Comment by thansidwell** [comment]
@markgoetz Yeah, good catch! I looked at that stylesheet and I would recommend changing it to all be the same font-family and make them different weights. It's the more natural and easy way to do it. https://share.cleanshot.com/1XKDWyRS

**Comment by thansidwell** [comment]
@markgoetz I checked out the vercel bot Preview! That's a super cool feature. 

It looks great! Everywhere got the new font, even the map legend and map tooltips!

The only place that doesn't have it was the Search field on the map. https://share.cleanshot.com/ZfVCXdyg

**Comment by markgoetz** [comment]
I'll take a look in a bit!  I'm hoping it'll be relatively easy - inputs are just one of those weird HTML elements that have their own opinions sometimes.

**Comment by nlebovits** [comment]
is this closed @markgoetz and @thansidwell ?

**Comment by markgoetz** [comment]
@thansidwell would have to confirm, but I closed another PR to fix the search field.

**Comment by thansidwell** [comment]
@nlebovits @markgoetz Yes, the search box font is fixed in the preview.

**Comment by thansidwell** [comment]
This seems live so I'll change the status to Live.
