### ISSUE TITLE
Add Icons

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#193]
As a user, I want to see a consistent set of icons used throughout the website. 

- The icon library being used in the prototype is Phosphor Icons. https://phosphoricons.com
- It's a very large set and we don't need to install the whole set. 
- I collected all the icons currently in use in the prototype and packaged them here. 
[feather-icons.zip](https://github.com/CodeForPhilly/vacant-lots-proj/files/13963901/feather-icons.zip)

- Find all the icons used in the website today, on the nav, controls and map https://share.cleanshot.com/r8DmgmYQ
- Swap them with the new icons 
- I'm not sure if the map icons are more locked down, but try to replace them as well. 
- Ensure that all the new icons are appearing. https://share.cleanshot.com/3k2F0k78
- The compass orientation icon you can ignore. I believe the control should be removed as uncessary and distracting. I wrote another ticket to hide or remove it. https://share.cleanshot.com/j31XN09h

**Comment by nlebovits** [comment]
https://github.com/phosphor-icons/react

**Comment by nlebovits** [comment]
@thansidwell flagging that map icons are mapbox defaults. I don't think we can replace them.
