### ISSUE TITLE
A11y - `aria-label` Take Action page's secondary navigation

### ISSUE THREAD

**Issue by marvieqa** [CodeForPhilly/vacant-lots-proj#195]
## Describe the task
The "Take Action" page has a secondary navigation. We should use `aria-label` to differentiate it from the primary navigation up top.

<details>
<summary> Screenshot</summary>

<img width="938" alt="Screenshot 2024-01-17 at 16 16 13" src="https://github.com/CodeForPhilly/vacant-lots-proj/assets/102739972/0d51261b-af8a-49f6-8e40-b8efcd235349">

</details>

[Figma Source](https://www.figma.com/file/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=1039-6122&mode=design&t=AYj3RUr9cBcRM3QB-4)

## Acceptance Criteria

- [ ] Use `<nav>` to wrap the secondary nav items
- [ ] Use `<ul>` to list the items
- [ ] Add `<aria-label="Take action information">` or something to that effect to differentiate it from the primary navigation up top.

**Comment by bacitracin** [comment]
Check if this is still relevant with new design
