### ISSUE TITLE
A11y - Provide a skip link

### ISSUE THREAD

**Issue by marvieqa** [CodeForPhilly/vacant-lots-proj#196]
## Description
Provide a `skip to main content` link, as the first tabbable element on the page to bypass repeated items in the header, and go straight to the main content.

Reference:
[WCAG 2.4.1 Bypass Block - Level A](https://www.w3.org/WAI/WCAG22/Understanding/bypass-blocks.html)

**Comment by nlebovits** [comment]
@all-contributors please add @marvieqa for a11y! :)

**Comment by bacitracin** [comment]
Random note: my favorite in the wild skip link examples are starbucks.com and github.com
