### ISSUE TITLE
Logo in header intrudes on map

### ISSUE THREAD

**Issue by nlebovits** [CodeForPhilly/vacant-lots-proj#200]
Currently, when you navitgate to the map page, the logo in the header comes down over part of the map. I'm not sure if this is an issue with the header size or what. @thansidwell what's the best way to handle?

![Screenshot 2024-01-17 at 11-19-43 Clean Green Philly](https://github.com/CodeForPhilly/vacant-lots-proj/assets/111617674/5eec6701-b1d8-4a97-9475-f7ef3b3a630b)

**Comment by thansidwell** [comment]
We need to let the header grow to the new height of the logo. There must be a fixed height declared on the header somewhere.
