### ISSUE TITLE
A11y - Update footer semantics, add aria-label

### ISSUE THREAD

**Issue by bacitracin** [CodeForPhilly/vacant-lots-proj#201]
## Describe the task
The current footer could use a semantic update & the nav element it uses needs an `aria-label` to differentiate it from the other navs on the page.

## Acceptance Criteria
- [ ] Change the structure of the footer from 
```
<nav>
  <header>
    <ul>
    </ul>
  </header>
</nav>
```

to

```
<footer>
  <nav aria-label="content info">
    <ul>
    </ul>
  </nav>
</footer>
```
- [ ] Give the nav item a descriptive `aria-label` since on some pages there will be up to 3 nav items. TBD on whatever you want ot call it. Currently for screenreader users it just reads as "nav" and will be hard to differentiate.

## Additional context
Example structure (ignore the bit about skip links) https://www.magentaa11y.com/checklist-web/footer/#example-footer

**Comment by nlebovits** [comment]
@all-contributors please add @bacitracin for a11y! :)
