### ISSUE TITLE
Add option to request the removal of specific properties from site

### ISSUE THREAD

**Issue by nlebovits** [CodeForPhilly/vacant-lots-proj#203]
Community organizations and other well-intentioned stakeholders may have a valid reason to want to remove a property from the website, e.g., to protect a community garden that they would like not to have developed. We should add an option to contact us and request that a property be removed. We also need to reserve the right to make a final judgement call on whether or not to remove something (i.e., we don't need to protect someone's parking lot or a negligent developers). So we'll need to figure out 1) where this goes and 2) how to word it.

@thansidwell and @willonabike any thoughts on where to put this + how to design it?

**Comment by nlebovits** [comment]
Possible language:

**Request to Remove a Property Listing**

If you represent a community organization or other stakeholder with a legitimate interest in a property listed on our dashboard, you may request its removal by contacting us [insert email link]. This option is intended to support community-driven initiatives, such as protecting local community gardens. 

In order to do this, please email us at cleanandgreenphl@gmail.com. Submit a detailed request for removal, including the specific address of the property and a thorough explanation of your reasons for requesting its removal. Documentation such as photos of the site in use are encouraged. We will review the reason for your request and respond as quickly as we can. In making our decision, we will consider whether we believe the request is reasonable and consistent with positive community impact and anti-gun violence initiatives. 

Our team reserves the right to make the final decision on whether a property will be removed from the dashboard. Please note that requests to remove properties solely for personal gain, such as protecting private parking spaces or assisting negligent developers, will not be entertained. By submitting a request, you acknowledge and agree that the final decision rests with our team, and not all requests may result in the removal of a property listing.

**Comment by willonabike** [comment]
As the goal is not to make it particularly easy - I suggest putting it
within one of the other pages that it logically aligns to. Maybe has an
expandable header in the take action page.



--
Will Budreau *(he/him)*
design:  willonabike.com <http://www.willonabike.com/>
contact: 650-218-WILL (9455) • LinkedIn
<https://www.linkedin.com/in/willbudreau/>

**Comment by thansidwell** [comment]
I can also think a logical place people might look is when a user is looking at the lot itself. 

Perhaps we could have a link or button at the bottom of each property listing that says something like "Request removal of this property" or "Report this property" and then it takes you to a page or part of a page with a description of how to request for the property to be hidden.

**Comment by nlebovits** [comment]
closed by #210
