### ISSUE TITLE
A11y - Primary Nav - apply hover styling on keyboard focus

### ISSUE THREAD

**Issue by bacitracin** [CodeForPhilly/vacant-lots-proj#206]
## Describe the task
When you hover over the nav items Intro/Map/About/Take Action the color changes and the text underline appears. Make it so that you see this same styling when the user is keyboard focused on the nav items.

You probably just need to add `:focus-visible` to wherever the hover styling rule is.

<img width="501" alt="Screenshot 2024-01-17 at 21 54 37" src="https://github.com/CodeForPhilly/vacant-lots-proj/assets/7329799/2564aecb-1e78-44e5-92c6-8550594c625b">

## Acceptance Criteria

- [ ] On any page TAB over to the primary nav items. You will notice that you can TAB two times per item, because you land first on the `<a>` tag, then on the nested `<button>` (suggested fix in https://github.com/CodeForPhilly/vacant-lots-proj/issues/205). On the first TAB landing, you should see the hover styling.

## Additional context
https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible

**Comment by markgoetz** [comment]
@bacitracin Is this one still valid?  I do see the focus state on tab.

**Comment by bacitracin** [comment]
@markgoetz hey there! This is still valid. There is a focus state on keyboard nav, but I'm asking for the hover styling to be added as well. 
So looks like this currently
<img width="217" alt="Screenshot 2024-02-08 at 20 39 19" src="https://github.com/CodeForPhilly/vacant-lots-proj/assets/7329799/b9838b3d-525c-47ca-be52-3840fa664b63">

Would like it to look like this on TAB focus.
<img width="229" alt="Screenshot 2024-02-08 at 20 39 14" src="https://github.com/CodeForPhilly/vacant-lots-proj/assets/7329799/8c540c88-65c9-4704-86bd-16e95baa4eda">

**Comment by bacitracin** [comment]
@markgoetz I saw you've got some PRs up around nav/links, should I be looking there for the fix?

**Comment by markgoetz** [comment]
@bacitracin Thanks for clarifying!  I have not yet taken care of this one.
