### ISSUE TITLE
Property Detail Adding Access/Transform information

### ISSUE THREAD

**Issue by willonabike** [CodeForPhilly/vacant-lots-proj#214]
Enhancements for in-context ACcess and Transform actions and links. todetails.

Property Details Panel: 
* Add styled link to property in Atlas
* Add L&I Violations as bullets

Table enhancements:
* Update ordering / grouping to Impact and Access considerations
* Split into two tables
* Add / style external links for key fields: RCO, Council Information
* Add Priority coloring along plain text for Priority attributes

Add Transform guidance Display a static set of transforms
Add Acquisition guidance - Display the set of access types that match this property, along with static text for each.

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1652510/5a1bb8b1-206e-4fb1-bf54-4aa1d9d553ec)
Live Design: [Figma Link](https://www.figma.com/file/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=1550-18290&mode=design&t=B3Vv7vZOxwLVoVqu-4
)

**Comment by willonabike** [comment]
@nlebovits Can you confirm data correctness, and flag anything that is not important for MVP?

**Comment by nlebovits** [comment]
Looks good to me! We're no longer considering sheriff sale as a data point because the city has frozen them (also, it effectively leads to buying the property anyway). We also don't have recommended lot transformations yet. But otherwise, looks good.

**Comment by willonabike** [comment]
Replacing the transformation with static recommendations and no sheriff sale.

**Comment by willonabike** [comment]
TY if you get a sec  while doing it, please list those we don't have here
so we can think ahead.
--
Will Budreau *(he/him)*
design:  willonabike.com <http://www.willonabike.com/>
contact: 650-218-WILL (9455) • LinkedIn
<https://www.linkedin.com/in/willbudreau/>
