### ISSUE TITLE
Quick fixes to navigation

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#221]
Make these small adjustments to the navigation https://share.cleanshot.com/RBZ0LyQS

- Remove the "Intro" option completely. It's unnecessary and awkward. If users want to get back to the home page they can click the logo. The home page is meant to be a quick intro and we don't to continue to emphasize it in the navigation. 
- Change the text "Map" to "Find Properties". This is much more clear that what you are doing matches the goals of the user. 
- Swap "Take Action" and "About" so "About" is far right. Somehow they got swapped. 

It should then match the prototype. https://www.figma.com/file/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=187%3A12709&mode=design&t=tPPiiAJPC04biO2f-1

The icon changes are in another ticket.

**Comment by nlebovits** [comment]
closed by #223
