### ISSUE TITLE
Install Hotjar

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#230]
We want to have ways to 
- Understand how users are using the website
- Get user feedback about the site

Hotjar seems a good option because it provides 
- Analytics
- Recordings
- In-app feedback surveys

I have an account and I created a Clean & Green Philly organization on it. I'll invite whoever wants access. 

Paste this code into the <head> of every page of the website. 

<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:3834123,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>

**Comment by nlebovits** [comment]
@thansidwell any idea how this works with React components? If I make a hotjar component and add that to our main pages, that should work fine, right?

**Comment by brandonfcohen1** [comment]
> @thansidwell any idea how this works with React components? If I make a hotjar component and add that to our main pages, that should work fine, right?

yeah, we use hotjar for work, you just install once and it works on the whole app, doesn't matter what's in the app

**Comment by nlebovits** [comment]
closed by #235
