### ISSUE TITLE
Improve Properity list controls

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#233]
Make these minor changes to the Property list controls
- Change the "Total Properties in View: **607**" to "**607** properties in view" https://share.cleanshot.com/TY35jWV6
- Remove the green from the number 607
- On the Download button remove the text download https://share.cleanshot.com/5kLXpvX1 
- Shift the view switcher control to appear after the Filter button and before the download https://share.cleanshot.com/P5xx8sWJ 

Bonus if you can do this
- Add a tooltip to the Download button saying "Download" 
- Add a tooltip to the View switcher button saying "View"

**Comment by nlebovits** [comment]
closed by #237

**Comment by thansidwell** [comment]
The status on this is "Live" but I'm not seeing it the live site.
