### ISSUE TITLE
Fix Priority Labels

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#238]
As a user would expect the High, Medium and Low badges on the properties list to match the color coding. Right now they are green. 

Make all the priority labels/badges on the property list color coded to match the map. https://share.cleanshot.com/Z9DC5g2p
- Make the "High Priority" badge red. Use these colors. https://share.cleanshot.com/XNHzVXz8
- Make the "Medium Priority" badge yellow. Use these colors. https://share.cleanshot.com/zCl7gr3h
- Make the "Green Priority" badge green. Use these colors. https://share.cleanshot.com/zCl7gr3h

Improve the map legend https://share.cleanshot.com/tgGHPZ2S
- Remove the word "Level" from "Priority Level". It's unnecessary. 
- Remove the word "Priority" from "Low Priority," "Medium Priority" and "High Priority." It's redundant. 
- Remove "Other" completely. I don't see any properites that are blue. 
- Swap the order of the Priority levels so that High is at the top and low at the bottom.

**Comment by nlebovits** [comment]
Flagging that some of these changes will have to happen in the data wrangling, not the UX (e.g., changing Low Priority --> Low). The rest of the stuff should be doable. Will add to my list.

**Comment by nlebovits** [comment]
closed (mostly) by #248

**Comment by thansidwell** [comment]
I see everything complete on the live site, so I'm moving this to Live.
