### ISSUE TITLE
Fix Property Card

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#239]
The Property card looks awkward and needs to more closely match the prototype. https://share.cleanshot.com/90pSSZgR

- Close the horizontal gap between card from 60px to 24px https://share.cleanshot.com/3KwNKMfy 
- Close the vertical gap between cards from 70px to 24px https://share.cleanshot.com/Bd3NPYM2
- Reduce the font size of the address title to around 18px https://share.cleanshot.com/1Rb2K1tM
- Change the address title to Title Case (Not ALL CAPS) https://share.cleanshot.com/1Rb2K1tM
- Reduce the font size of the subtitle info to around 14px https://share.cleanshot.com/Lf2t5lwC
- Remove "Click here for Atlas Info". https://share.cleanshot.com/ry9RYY3c
- Reduce the height of the street view images to 160px. https://share.cleanshot.com/mZKQFRk7

**Comment by nlebovits** [comment]
closed by #241
