### ISSUE TITLE
Fixes to View Property

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#246]
- Hide the property list controls when you are viewing the details of a single property. https://share.cleanshot.com/XJZMl4JC
- Increase the left, right, and bottom padding from 16px to 24px. https://share.cleanshot.com/bDvLlQl7
- Lower the font size for the content (table and paragraphs) to around 16px https://share.cleanshot.com/9pX6YN03 
- Add a right arrow to the back button. https://share.cleanshot.com/rKj2jjg2
- Change the back button from a gray background to a white or transparent background. https://share.cleanshot.com/rKj2jjg2
- Change the "View this property on Atlas" to a simple white/transparent Atlas button with an arrow out icon. And align it with the address. https://share.cleanshot.com/x3J3cRVR
- Make the property address Title Case, not All Caps. https://share.cleanshot.com/zyy30THN

**Comment by 19ewalker** [comment]
I can take this one !

**Comment by thansidwell** [comment]
@19ewalker, great! I assigned this to you and changed the status to "In Development" in case you can't or haven't done it.

**Comment by nlebovits** [comment]
@19ewalker flagging that we don't have have a save button enabled in the app, so don't worry about adding it yet

**Comment by nlebovits** [comment]
closed by #296
