### ISSUE TITLE
Fix Additional Map Issues

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#247]
- Make all the text in the map legend title case instead of all caps. Priority, High, Medium, and Low.  https://share.cleanshot.com/vFJd8pvj
- Make the text High, Medium, and Low use a darker shade of gray. It's too light for people with vision problems. 
- Remove the "Other" item in the legend. https://share.cleanshot.com/yGgKHVdN
- Add an info icon next to the heading Priority. When a user hovers over a tooltip should appear. The exact text can be added later. https://share.cleanshot.com/jVH0dk35

**Comment by nlebovits** [comment]
flagging that this will probably require us to fork + modify our own copy of https://github.com/markusand/mapboxgl-legend

maybe an opportunity to contribute to that package

**Comment by Moylena** [comment]
@thansidwell  @nlebovits  @brandonfcohen1  Looks like this was deployed, however it's missing the "i" icon - can this be updated and pushed or should this become a new ticket?

**Comment by thansidwell** [comment]
I think adding the "i" icon with the tooltip can be it's own ticket. I'll change the status here to Live.
