### ISSUE TITLE
Fixes to Home page headline

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#250]
- The text "by as much as 29%" drops to the next line when it doesn't need to. https://share.cleanshot.com/zjv0wFQv  Adding this CSS fixes it. https://share.cleanshot.com/w7d0pwWX 
- The headline is quite big. Reduce the font size from 48px to something closer to 36px. https://share.cleanshot.com/YYNTNDl3
- Right now the headline has no gap between the lines. https://share.cleanshot.com/m648M7TZ  Increase the line-height to something close to 47px or 3rem https://share.cleanshot.com/1FM3DC2s
- The headline and the other text are uncomfortably close. Increase the gap between them to something around 60px. https://share.cleanshot.com/dCjV0zVR
- The headline text is so thin it doesn't match the rest of the site. Change it to Regular weight. https://share.cleanshot.com/tfMsYxzf
- The headline needs a period at the end of it. https://share.cleanshot.com/BFP2BFXR

**Comment by nlebovits** [comment]
closed by #275
