### ISSUE TITLE
Map bug: Properties turn blue

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#251]
As I look around the map big groups of properties on the map switch to blue matching the "Other" type on the legend. https://share.cleanshot.com/fZhFp0CY

The badges in the list also go gray. https://share.cleanshot.com/6r0S5FTP

Here's a video of the odd behavior. https://share.cleanshot.com/57JpNmtj

**Comment by nlebovits** [comment]
Yeah, it stems from some changes I made to the labels for priority level. An easy fix.

**Comment by nlebovits** [comment]
closed by #266

**Comment by thansidwell** [comment]
This seems fixed on the site, right @nlebovits?

**Comment by nlebovits** [comment]
Yeah, it's been corrected @thansidwell
