### ISSUE TITLE
Bug: Gap appearing above list controls

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#253]
On the property list and simple view sometimes a gap appears above the controls. I think it's related to how sometimes I can see double scrollbars on the right. 

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/a39f7135-8512-4d22-bd1a-fa23e8c260da)

Here's a video. https://share.cleanshot.com/XYG4ByFk

**Comment by nlebovits** [comment]
closed by #283
