### ISSUE TITLE
Responsive: Make Navigation Responsive

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#259]
Right now on small devices, the navigation becomes hidden. https://share.cleanshot.com/xvPmddB0

Make these changes to make the app responsive and accessible on mobile devices. 

- Make the navigation not hide on mobile. https://share.cleanshot.com/BvXjnLDy
- When the viewport reaches a smaller size and can no longer fit showing all the navigation option, somewhere around 600px https://share.cleanshot.com/TN3sXRmq
- Display a button saying "Menu" with a three-line menu icon 
- When a user clicks on the "Menu" icon a dropdown should appear with the navigation options in it. They should also include the icons. https://share.cleanshot.com/x9m2L0M8
- Clicking on these navigation items should navigate user to the different pages. 

Here's a prototype you can reference. https://www.figma.com/file/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=203%3A14992&mode=design&t=BCw3uF1EeDQPocXH-1

**Comment by Moylena** [comment]
UPDATED DESIGN: https://www.figma.com/proto/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?page-id=187%3A12602&type=design&node-id=2592-30019&viewport=-657%2C-623%2C0.1&t=fqZvOvLyE9qv7AAV-8&scaling=min-zoom&starting-point-node-id=2592%3A30019&hide-ui=1

**Comment by thansidwell** [comment]
Like @Moylena noted. The options in the navigation have changed but the experience hasn't changed.

**Comment by Amberroseweeks** [comment]
I'd like to assign this to myself, if this task is open. I worked on the desktop view. I just wonder what tablet view might look like and if there are any specific breakpoints we would like to follow?

**Comment by Moylena** [comment]
@thansidwell  Do we have specific breakpoints for mobile, tablet, and (related to another ticket on max width) desktop?

**Comment by thansidwell** [comment]
@Moylena Sorry! I should have specific break points, but I haven't laid them out. It seems that @Amberroseweeks used her own judgment and it turned out fine.
