### ISSUE TITLE
Responsive: make Find page Mobile Friendly

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#260]
The Find page needs to work on mobile devices.

- Add a button that toggles between the map and list views of properties
- Make the property card list appear in one column
- When someone clicks on a property on the map it should switch to the property detail view

Here's a link the the prototype in Figma. https://www.figma.com/file/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=2421%3A22712&mode=design&t=EYanZQnoOdgWCTls-1

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/49b1f541-5c25-4699-b826-dc1ada7a8dfc)

**Comment by Moylena** [comment]
NOTE design is updated but doesn't impact the requested changes

**Comment by amyyeung17** [comment]
Hello! I would like to be assigned to this issue if it's available. :)
