### ISSUE TITLE
Responsive: Fix padding and width with content pages

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#261]
Right now the text on content pages...

- Goes very wide, past the standard recommended width for ideal reading. https://share.cleanshot.com/hb90DnPD
- On mobile size screen there's no padding. https://share.cleanshot.com/gcQ05CQP

Make the fixes https://share.cleanshot.com/FqW84lqb

- add a 1000px max-width to the 
- Add a 20px padding on mobile size screens

**Comment by bacitracin** [comment]
@jgaye iIsaw that there was a PR merge, but also a revert. What's the status on this ticket - still in development or live?

**Comment by jgaye** [comment]
@bacitracin it's still in development. I haven't had the chance to redo the changes since the directory architecture changes, I hope to do as new PR tomorrow

**Comment by jgaye** [comment]
> [@bacitracin](https://github.com/bacitracin) it's still in development. I haven't had the chance to redo the changes since the directory architecture changes, I hope to do as new PR tomorrow

New PR in out @bacitracin

**Comment by thansidwell** [comment]
@jgaye I see it's been done to the Get Access and Transform pages. Could you also do it to these pages? 
- Home
- About

**Comment by jgaye** [comment]
> > @jgaye I see it's been done to the Get Access and Transform pages. Could you also do it to these pages?
> > 
> > * Home
> > * About
> 
> @thansidwell because Home and About are on two columns, I'm not sure it's worth adapting with the same max-width, as each column is already smaller than half the size of the screen. Additionally, the column format also gives the mobile padding by default.
> 
> How would you apply the max-width for those pages?

@thansidwell Asa very quick demo, this is how the About page would look like with the max-width applied to the whole page:  
![image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/4049458/f326ef3a-1099-4605-9c4c-321f356555b0)

**Comment by jgaye** [comment]
@thansidwell sorry for all the messages.
I updated the PR with a max width for About and Home. that is the same as the other pages, and adapted the columns so that there is no double padding applied. Please have a look and let me know if that's good.

**Comment by thansidwell** [comment]
@jgaye With some other tickets we're removing the columns with the new content coming in.

**Comment by thansidwell** [comment]
I approved the pull request.

**Comment by Moylena** [comment]
Should this be considered closed? I see in the PR that there is 1 pending review? Not sure if that leaves this in limbo

**Comment by thansidwell** [comment]
@Moylena, I'm not sure. 

@jgaye, what's the status on this? It seems like you're really close. Where can we take a look at the changes?

**Comment by jgaye** [comment]
I would not merge as is, as the current code is creating some requirements for future developers that are not worth it (see the discussion on the PR).
Currently I know what to do, but I would restart from staging to avoid merge issues. I don't know when I will have time to do this.
Do not hesitate to re assign is the schedule needs it

**Comment by paulhchoi** [comment]
Seems like this was merged in a few weeks ago. We can close this and monitor for any issues going forward.
