### ISSUE TITLE
Fix Zoom Level Limit issue

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#271]
Make the properties not disappear as you zoom out. https://share.cleanshot.com/ymktG1jW

A user should be able to zoom out and see the status of properties across all of Philadelphia.

**Comment by brandonfcohen1** [comment]
there are too many features in the dataset to render tiles at lower zooms.

in time I can explore other hosting solutions besides mapbox, but not something we can get done before the deadling

some ideas:
- add a popup saying to zoom in to see properties
- cluster into points at lower zooms
- don't allow zooming out past where data is visible

I added the popup back and will close this ticket. we can re-open if we want to and have the bandwidth to explore further
