### ISSUE TITLE
Bug: Sometimes pages don't load

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#278]
About 10% of the time, when I try to navigate to these pages, they don't load.  
- Get Access
- Transform a Property
- Summary

Here's a video of it happening. https://share.cleanshot.com/CSxknnwB

It happens in both Safari and Chrome. It's not a high priority. It's hard to replicate. I'm not sure what's causing it.

**Comment by nlebovits** [comment]
I've been having the same issue. I think it ties back to when I changed the menu option to a dropdown. I'm using a nextui dropdown selector but I'm wondering if three's a better way to do it. It seems like if you click on the left side of the menu subitem, it works fine, but other times it doesn't load. Not sure what the deal is, though. Maybe @markgoetz or @brandonfcohen1 have suggestions for now to refactor? issue is in Header.tsx, I think:

```
      <Dropdown>
        <DropdownTrigger>
          <Button size="md" className="flex items-center hover:text-blue-500 hover:underline bg-white">
            <Hand className="h-6 w-6" aria-hidden="true" />
            Take Action
          </Button>
        </DropdownTrigger>
        <DropdownMenu aria-label="Take Action">
          <DropdownItem key="get-access">
            <Link href="/get-access">Get Access</Link>
          </DropdownItem>
          <DropdownItem key="transform-property">
            <Link href="/transform-property">Transform a Property</Link>
          </DropdownItem>
        </DropdownMenu>
      </Dropdown>
```

**Comment by markgoetz** [comment]
@nlebovits @thansidwell Is this issue still valid, now that the PR was merged?

**Comment by bacitracin** [comment]
Closing this because I'm pretty sure it's been addressed and is live
