### ISSUE TITLE
Styling: Add accessible color scheme

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#287]
The colors we're using have problems. 

- Text doesn't pass contrast standards for people with vision imparments. 
  - Primary button https://share.cleanshot.com/lN1kGtLG
  - Badges https://share.cleanshot.com/J0rLSmtZ
  - Nav buttons https://share.cleanshot.com/Cg2X2cwf
  - Legend text https://share.cleanshot.com/TBphxpG1

- Not enough contrast on the map legend colors https://share.cleanshot.com/2T5GpQxL

- These colors we're picked without really building out shades that could be used.  

Add this set of colors into the site. 

```
/* COLORS */
:root {
  --gray-0: #ffffff;
  --gray-100: #eaf3f7;
  --gray-200: #ccdce3;
  --gray-300: #8a9da3;
  --gray-400: #6b7a80;
  --gray-500: #586266;
  --gray-600: #323f43;
  --gray-700: #1b343e;
  --gray-800: #112a34;
  --gray-900: #03141b;
  --gray-1000: #000000;
  --green-100: #e9ffe5;
  --green-200: #c2f5ba;
  --green-300: #95e089;
  --green-400: #4bb23b;
  --green-500: #289a16;
  --green-600: #188706;
  --green-700: #0c5c00;
  --green-800: #094400;
  --green-900: #062d00;
  --blue-100: #e5f8ff;
  --blue-200: #bae4f5;
  --blue-300: #84d5f5;
  --blue-400: #57bee7;
  --blue-500: #2496c4;
  --blue-600: #077099;
  --blue-700: #004560;
  --blue-800: #003144;
  --blue-900: #00202d;
  --red-100: #ffe9e5;
  --red-200: #f7c4bc;
  --red-300: #ff8370;
  --red-400: #f9492c;
  --red-500: #cd3b24;
  --red-600: #a7230f;
  --red-700: #600d00;
  --red-800: #440900;
  --red-900: #2d0600;
  --yellow-100: #fff5d0;
  --yellow-200: #fff0bb;
  --yellow-300: #ffe68b;
  --yellow-400: #f1c936;
  --yellow-500: #cda821;
  --yellow-600: #876b06;
  --yellow-700: #604b00;
  --yellow-800: #443500;
  --yellow-900: #2d2300;
}
```

If possible, remap all the colors references in the website to these new values. That might not be easy to do. 

If we make the changes one by one here's the basic changes we should make with this ticket. 

- All text throughout the site should be gray-900 by default
- Change homepage headline to green-500 https://share.cleanshot.com/SZ9cnCDn
- Change the badge colors to use background 200 and text 800. https://share.cleanshot.com/y2W9nxCx 
  - We could use light text on a dark background, but it gets much darker and heavier looking to pass contrast standards. Dark background https://share.cleanshot.com/vXG323LV vs. light background badges https://share.cleanshot.com/ZcZhFNxY
- Change the primary button background color to green-600 https://share.cleanshot.com/Rl7rRMkT
- All links should be blue-600. https://share.cleanshot.com/brb5Lq5b

Note: We need to make sure we are using variables using CSS variables or SASS variables, and avoid ever hard coding the colors. https://www.w3schools.com/css/css3_variables.asp

The corrects to the map colors need some design work and probably their own ticket.

**Comment by paulhchoi** [comment]
@thansidwell have you considered paring this list down to just the main colors that you use in your figma mockups? I've found that enforcing a much tighter color palette through tailwind's config file helps in overall style cohesion, as well as changing the naming convention from "green-" "red-" to possibly "primary-" "secondary-", etc

**Comment by thansidwell** [comment]
Yes, you certainly could do that. Often when building out design systems we'd use the green, red, and blue color levels (green-500) and then have aliases or mixin with how they will be used: primary, danger, and info (primary-500). Why not just use the utility names? Sometimes you want to use red but you aren't using it to convey danger. Adobe does it this way. https://share.cleanshot.com/2N94qLst Now granted maybe that's overboard. I'm happy for you to do whatever you think best.

**Comment by jgaye** [comment]
@thansidwell if I do the changes locally, is there a way for me to test locally if my page pass the contrast standards? Is there an accessibility tool to test that?

**Comment by paulhchoi** [comment]
> @paulhchoi Yes, you certainly could do that. Often when building out design systems we'd use the green, red, and blue color levels (green-500) and then have aliases or mixin with how they will be used: primary, danger, and info (primary-500). Why not just use the utility names? Sometimes you want to use red but you aren't using it to convey danger. Adobe does it this way. https://share.cleanshot.com/2N94qLst Now granted maybe that's overboard. I'm happy for you to do whatever you think best.

Yea that makes a lot of sense, I can align with the use of the actual colors green/red/blue

**Comment by Amberroseweeks** [comment]
Hi, if no one is working on this, can I please be assigned this task?
