### ISSUE TITLE
Fix initial map zoom

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#289]
When the "Find" page loads the map loads at a zoom level where ...  https://share.cleanshot.com/5cj9dRgt
- No high-priority properties are in view
- Almost only low-priority properties are in view

Zoom out so the whole area of Philadelphia is in view and you can see high-priority properties are in view. https://share.cleanshot.com/C9N7K52w

There's another ticket to fix the properties from disappearing when it's zoomed out.

**Comment by brandonfcohen1** [comment]
I set the map to load in North Philly instead of Center City
