### ISSUE TITLE
Fix homepage headline line-breaking

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#290]
The headline is line-breaking in weird ways on laptops. https://share.cleanshot.com/lnrbkSk4
On larger screens, it looks ok. https://share.cleanshot.com/wk8dQ85b

Make these changes. 

- Remove the awkward line breaks on both the headline on the left and supporting text on the right. 
  - Probably best done by taking the text out of these blocks. 
- Avoid breaking the words "reduce gun violence" and "as much as 29%." apart to seperate lines.
  - This can be done by adding "display:inline-block" https://share.cleanshot.com/zBsbcbgw

The other text block is also line-breaking in an odd way on laptops. https://share.cleanshot.com/VMLhThnC

- Remove the block spans around it.

**Comment by brandonfcohen1** [comment]
per convo w @thansidwell - add padding to the right
