### ISSUE TITLE
A11y: "Find Properties" and "Learn more" text doesn't pass the minimum contrast requirement

### ISSUE THREAD

**Issue by marvieqa** [CodeForPhilly/vacant-lots-proj#297]
## Description

The text color used for "Find Properties" & "Learn more" doesn't match the minimum contrast requirement of 4.5:1 ratio. It needs a darker green to pass.

EDIT by @bacitracin as of 3/9/2024:[ The design has been updated](https://www.figma.com/file/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=2592-30019&mode=design&t=Dqn1uDicGqfXkT5v-0) and these buttons have moved, but contrast still needs to be checked. Use https://colourcontrast.cc/ and make sure it passes to AA Large, AAA Large, and AA Normal.

OLD DESIGN:
<img width="439" alt="Screenshot 2024-01-30 at 16 02 42" src="https://github.com/CodeForPhilly/vacant-lots-proj/assets/102739972/3265f217-aa2b-4f43-ad5c-40698f5be28f">

NEW DESIGN:
![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/7329799/0a5611ae-2369-438c-9493-aac3f56686a2)
![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/7329799/660eedc8-0589-4820-8531-b0ca8a1e56f6)

- Source page: https://staging.cleanandgreenphilly.org/
- WCAG Criteria: [1.4.3 Contrast (Minimum) Level AA](https://www.w3.org/WAI/WCAG22/Understanding/contrast-minimum.html)

**Comment by marvieqa** [comment]
Note: For anyone picking up, we should ping @thansidwell to see what color we can work with in line with the overall design.

**Comment by bacitracin** [comment]
Updated 3/9/2024, the design has changed but buttons still need to be checked for contrast

**Comment by Moylena** [comment]
@thansidwell should we determine what color passes then update the Figma file with the final result?

**Comment by thansidwell** [comment]
@Moylena This is now resolved. The new buttons all pass contrast requirements. I think we can archive this ticket. 

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/6cf85bc3-bbf8-4692-bb5a-9d26db5a567a)

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/e8b554fa-c055-4b73-9696-717605343fd7)

**Comment by marvieqa** [comment]
closing ticket as resolved!
