### ISSUE TITLE
A11y: Define the `<h1>` in Find Properties page

### ISSUE THREAD

**Issue by marvieqa** [CodeForPhilly/vacant-lots-proj#302]
## Describe the task

Screen reader users primarily use headings to scan the page. In the "Find Properties" page we do not have a heading level 1.  The most important information on the page is the number of properties in view. Let's make `x properties in view` as the `<h1>` in the page.

<details>
<summary> Screenshot </summary>

<img width="1475" alt="Screenshot 2024-01-30 at 21 27 17" src="https://github.com/CodeForPhilly/vacant-lots-proj/assets/102739972/905e924b-d8a9-424c-bd0a-c7cb2e5dba19">

</details>

## Acceptance Criteria

- [ ] Keep the style, but mark it up as `<h1>`

**Comment by bacitracin** [comment]
PR: https://github.com/CodeForPhilly/vacant-lots-proj/pull/352
