### ISSUE TITLE
Jump into Street view

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#303]
I believe when users look at properties they will likely want to...

- See a larger view of the photo of property
- Look at the buildings or lots next to the property 
- Look up and down the whole stree to get an understanding of the neighborhood

So add these capabilities

- Add a full screen icon button over the street view photo top right https://share.cleanshot.com/ZqYVH8V9 -  [Figma Prototype](https://www.figma.com/file/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=1730%3A27007&mode=design&t=i4xIuRmInigKVwwV-1)
- If a user clicks it it opens up a full screen view of the Google Street View of that address. https://share.cleanshot.com/2DvDd1pb - [Figma Prototype](https://www.figma.com/file/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=187%3A12722&mode=design&t=i4xIuRmInigKVwwV-1)
  - I believe we can use the Google Street view Embed feature. https://share.cleanshot.com/VDZw3Qsq

Here's video explaining the whole thing. https://share.cleanshot.com/5R0KRwDy

**Comment by paulhchoi** [comment]
Heads up regarding this ticket, I believe this may require a Google API key for the [Geocoding API](https://developers.google.com/maps/documentation/geocoding/overview) and the [Maps Embed API](https://developers.google.com/maps/documentation/embed), which would enable the usage of "given an address, provide an embedded streetview" — is a shared key available for use, or could an admin generate one?

To explain, in the implementation example video, Nathaniel gave the example of utilizing the "Google Map > Share > Embed a Map" function available through [maps.google.com](maps.google.com), but upon further inspection, while manually possible, this doesn't seem programmatically possible without the APIs (as in, it doesn't seem possible to derive an embeddable map URL just from the address as a string).

For implementation details, we would need to use the [Geocoding API](https://developers.google.com/maps/documentation/geocoding/requests-geocoding#geocoding-lookup) to, given an address, generate a longitude & latitude, and then use those as inputs to the [`streetview mode`](https://developers.google.com/maps/documentation/geocoding/requests-geocoding) of the Maps Embed API to retrieve an embeddable streetview URL.

**Comment by thansidwell** [comment]
Interesting. So @paulhchoi how difficult would this be to do? Also, don't we have to pay for the Google API? I'm hesitant to add another expense when we are already paying for Mapbox.

**Comment by thansidwell** [comment]
@brandonfcohen1, what do you think of this feature and @paulhchoi 's comments? How much work would be implementing this be? Does the Google API cost extra money? How much? 

I wonder how big is the street view image we get from Google? Do we have a large version? Could we just build for users a full-screen view of the image? If we get a really large version of the image, perhaps we could do a pan left and right panorama experience?

**Comment by brandonfcohen1** [comment]
We actually are using Google Cloud to get the Streetview images and I'm hosting them on GCP storage. We have the free trial credit but I'd rahter not add more services that we might need to pay for.

My halfway recommendation would be to open streetview in a new tab at that address. We don't need to use the geocoder since we can get the coordinates from the map.

Thoughts?

**Comment by paulhchoi** [comment]
Understood; if we're ok with staying scrappy, I opened up a [PR](https://github.com/CodeForPhilly/vacant-lots-proj/pull/387) and would be interested on your thoughts on how I'm generating the google map embed URL here: https://github.com/CodeForPhilly/vacant-lots-proj/commit/82f435e6859f57d5d7434ccc6f015a3d98acf394#diff-90f0b4840550f8b5723a8f4b5d882bd090cabdd20fe28f8519994fd61ee9251fR39-R42. Caveats are listed in the PR description.

**Comment by thansidwell** [comment]
I just looked over @paulhchoi 's solution, and though it's not perfect, it's still great and does the job.

**Comment by brandonfcohen1** [comment]
huh, that's annoying, bc using the static image API you can enter an address and it'll orient the camera to the house, like I did here:

https://github.com/CodeForPhilly/vacant-lots-proj/blob/d74a13dc1bf044027f3e97afc8659bf10dbe6532/data/src/streetview.py#L43-L44
