### ISSUE TITLE
Bug: initial Zoom out and back in shows 0 results with visual map

### ISSUE THREAD

**Issue by willonabike** [CodeForPhilly/vacant-lots-proj#308]
Steps:
1. Load Map view: Observed: ~15,000 property count
2. Zoom out: Shows 0 properties, message indicating zoom in
3. Zoom in: 
Expected: Shows same 15,000 property count
Actual: Shows 0 properties, although map shows outlines

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1652510/745cefe8-3fdb-4174-bb31-ab454a93379c)

**Comment by thansidwell** [comment]
We've talked to @brandonfcohen1 about this issues. We would all like the properties to appear when you back out, but Mapbox caps the number of shapes they can have at one time, and zooming out blocks this. I don't know if @brandonfcohen1 has figured out a way to resolve this.

**Comment by Moylena** [comment]
@brandonfcohen1  any progress here?

**Comment by brandonfcohen1** [comment]
> @brandonfcohen1 any progress here?

this was done with the new tile structure
