### ISSUE TITLE
results appear blank when new results have fewer pages than currently selected

### ISSUE THREAD

**Issue by willonabike** [CodeForPhilly/vacant-lots-proj#309]
Steps: From Maps view w/15k results
1. Choose Page 10
2. Enter a search address e.g. 1234 Locust
3. Pans to the section and shows the search count
Expected: Shows the results in the right side, first page selected.
Actual: No results shown.  No page selected.

Workaround: 
4. Click on 1

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1652510/7f4c8c48-4f2d-4b1f-a002-c0a70acb27d3)

**Comment by jgaye** [comment]
@willonabike I haven't been able to reproduce this issue on the production website or on the staging branch, I think this might be fixed?  
Or I missed a step to reproduce?  

https://github.com/CodeForPhilly/vacant-lots-proj/assets/4049458/90bab920-2306-4845-b58c-ad6cbd36836b

**Comment by thansidwell** [comment]
This issue appears resolved to me too. I'm going to close this issue or archive it.
