### ISSUE TITLE
On initial load, shows "0 Results" while loading

### ISSUE THREAD

**Issue by willonabike** [CodeForPhilly/vacant-lots-proj#310]
1. Load the initial /maps page, observe while loading
2. Observed: Page elements start to load
3. After a short time
Expected: Informs user that results in progress e.g. “Loading Results”
Actual: Shows “0 Properties in view”
4. After full page load, correctly updates to the “15k Properties in view”

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1652510/7a65284f-55a3-46e5-821d-d672ed1b2b70)

**Comment by jgaye** [comment]
@brandonfcohen1 @willonabike @thansidwell  
When you have time, my PR is waiting for review [here](https://github.com/CodeForPhilly/vacant-lots-proj/pull/379)  

It's very nice how you have a branch App auto-built for testing with Vercel :+1:

**Comment by thansidwell** [comment]
This looks great!
