### ISSUE TITLE
Fix Detroit Future City quiz link

### ISSUE THREAD

**Issue by bacitracin** [CodeForPhilly/vacant-lots-proj#313]
**Describe the bug**
Currently appears as text and not a link:

<img width="874" alt="Screenshot 2024-02-05 at 10 27 27" src="https://github.com/CodeForPhilly/vacant-lots-proj/assets/7329799/9165b95e-c8e9-4edd-b296-6e873c18c01f">

**Comment by AZBL** [comment]
Hi I just took care of this.

**Comment by AZBL** [comment]
Did it again but opened to staging this time.

**Comment by nlebovits** [comment]
thanks @AZBL! closed by #314
