### ISSUE TITLE
A11y: Shorten the width of large blocks of text

### ISSUE THREAD

**Issue by bacitracin** [CodeForPhilly/vacant-lots-proj#325]
## Describe the task

Long lines of text can be hard for users with visual difficulties to keep track of their place. 
WCAG suggests a maximum of 80 characters per line, which isn't a requirement but a suggestion.

We're currently at 179 characters on this page, maybe we can bring it down a little? Just something to play with, see how it feels.

<img width="1332" alt="Screenshot 2024-02-08 at 20 56 18" src="https://github.com/CodeForPhilly/vacant-lots-proj/assets/7329799/7098d746-5e1b-4bbb-9d23-2e1b25ffcbf1">

## Acceptance Criteria

- [ ] No acceptance criteria, this is just a UX suggestion
## Resources
https://www.w3.org/WAI/tutorials/page-structure/styling/#:~:text=Line%20length,characters%20or%20less%20are%20shown.

**Comment by Moylena** [comment]
@thansidwell could you determine a max width for the container to implement perhaps?

**Comment by Moylena** [comment]
Ticket 261 addresses this in part. Max content width is now 1000px, this takes the character count down to 126. In an effort to get tickets done for the competition, going to close this!
