### ISSUE TITLE
Use links when loading pages and property details

### ISSUE THREAD

**Issue by marvieqa** [CodeForPhilly/vacant-lots-proj#342]
## Description

Consider using links when loading the pages in the pagination and when loading the property details, so that users can also use the browser's back button to go back.

For example, the back button we provide on the property details page can be missed or forgotten by a user who's scrolled all the way down. A user may use the browser's back button to go back to the results, and at this point, they will be taken completely out of the Find Properties page, which would result to an unfavourable user experience.

**Comment by paulhchoi** [comment]
an additional suggestion may be to add the property id as a search parameter ([NextJS's `useSearchParam` hook](https://nextjs.org/docs/app/api-reference/functions/use-search-params) would work here ) to the url, so that in addition to fixing the back-button UX, you could also share a specific lot with someone else through the url (which is currently not possible)

**Comment by paulhchoi** [comment]
@brandonfcohen1 — I was starting to work on this, but was unable to get a specific `feature` or `property` given an `OPA_ID` (which, given a search parameter of something like `https://cleanandgreenphilly.org?id=12345`, would pull the id from the url, fetch a matching property, and set it to the page's state) — is there direction you can provide in terms of a function or endpoint that may be available to make this fetch? the only feature set I was able to find came from the mapbox source, which required the map to load first before a feature could be provided, and was wondering if there was a more direct way.

**Comment by brandonfcohen1** [comment]
> @brandonfcohen1 — I was starting to work on this, but was unable to get a specific `feature` or `property` given an `OPA_ID` (which, given a search parameter of something like `https://cleanandgreenphilly.org?id=12345`, would pull the id from the url, fetch a matching property, and set it to the page's state) — is there direction you can provide in terms of a function or endpoint that may be available to make this fetch? the only feature set I was able to find came from the mapbox source, which required the map to load first before a feature could be provided, and was wondering if there was a more direct way.

As the app is currently set up this would be a challenge. The simplest way would be to basically load the map and then query the features, but might take a few seconds.

If this becomes a high priority I'll have to come up with another way to get the property data into memory.
