### ISSUE TITLE
A11y: Fix “Take Action” and “About” menu accessibility issues

### ISSUE THREAD

**Issue by marvieqa** [CodeForPhilly/vacant-lots-proj#344]
## Description

Multiple Accessibility issues are observed in the  “Take Action”  & “About” menus. 

### Keyboard:

- Pressing ENTR or SPACE does nothing on a menu item; it doesn’t take me to the location
- Keyboard focus is trapped in the menu when I press the TAB key while it is expanded. Though users can eventually get out of this state (ex. Pressing ESC or ENTER), this is not a standard menu behavior, and could throw off users with varying levels of cognition.

### Screen Reader:

Screen Reader experience is inconsistent between different browser & screen reader combos. It can perform the intended actions (if links are working) but with difficulty. Here are some examples

- The screen reader announces an invisible Dismiss button.
- The reading order needs to be corrected. When the menu is expanded, the screen reader focus is somehow at the bottom of the menu. The user is forced to backtrack to find the menu items.
- In NVDA + FF (popular combo) the screen reader announces extra information and states that are confusing to screen reader users. It doesn’t switch to focus mode when the custom widget is activated. Also, similar to Voice Over, it announces the invisible element “Dismiss” button.

### Demos

I have recorded experience in VO and NVDA. If you need JAWS please let me know.

[Experience in Voice Over + Safari](https://www.loom.com/share/f262a57cf1594ba0802de40102b8951f?sid=deede675-fd09-4438-ae54-5f5694ab9653)
[Experience in NVDA + Firefox](https://www.loom.com/share/006656c29c8e487c9b94e770627f2b4a?sid=f8029562-887e-4685-89b5-38c9a12efb6d)
[Sample desired behaviour in VO](https://www.loom.com/share/3c4fb97c0e35440a8b7112467260ebb1?sid=e729699f-4477-483a-8b03-1ce5b786e2d0)
[Sample desired behaviour in NVDA](https://www.loom.com/share/aaa3907bd81e435b820aa557ade68b27?sid=0bee4f2e-1ee7-46ef-a428-7835352f32f3)

## Recommendations

The library used doesn’t appear to be as accessible as advertised. I’m not sure how flexible the customization is for the library, but we should consider just writing our own menu button using WAI-ARIA recommended pattern, so that we are sure that it works consistently across the board. 

- Use the WAI-ARIA pattern for a navigation menu button https://www.w3.org/WAI/ARIA/apg/patterns/menu-button/examples/menu-button-links/
- We can also use explore using a disclosure type navigation: https://www.w3.org/WAI/ARIA/apg/patterns/disclosure/examples/disclosure-navigation/

**Comment by Amberroseweeks** [comment]
Hi, i'd like to assign myself this issue.

**Comment by bacitracin** [comment]
@Amberroseweeks assigned! There have been some changes since this ticket was created, so pressing "ENTER" does work now, but I think the rest still stands.

**Comment by Amberroseweeks** [comment]
@bacitracin Update on this task: The desktop view no longer has the dropdown in the new design so I am just working on matching the current design and ensuring the a11y is present in the current nav. I hope that's okay, should I edit this task title or delete and make a new one? I am a little concerned about the use of color as meaning for a selected menu state but we can discuss Tuesday

Also, I found that the NEXTUI library has some known issues for their dropdown items. They are inserting <span> elements within the menu items and also a <span> element on the menu that purposely traps the focus using focus-scope. This may have been added for modals as they need a focus trap but not a menu dropdown. https://github.com/nextui-org/nextui/issues/2357

**Comment by bacitracin** [comment]
@Amberroseweeks Let's continue using this issue for now, just add edits. NextUI is unfortunately inconsistent in its a11y support. Some of the components are pretty great (tooltips!) some meh and some are just wrong. We are not wedded to NextUi component implementation, so feel free to rewrite components in semantic HTML without the library.
