### ISSUE TITLE
BUG: React/JSX errors on /get-access

### ISSUE THREAD

**Issue by brandonfcohen1** [CodeForPhilly/vacant-lots-proj#372]
**Describe the bug**
React/JSX errors on https://www.cleanandgreenphilly.org/get-access

**To Reproduce**
1. Go to https://www.cleanandgreenphilly.org/get-access
2. Open Console

**Expected behavior**
No Errors

**Comment by liathirsh** [comment]
Hi @brandonfcohen1, I'd like to take on this ticket!
