### ISSUE TITLE
Unable to see contribution docs from README.md

### ISSUE THREAD

**Issue by BayLadyCoder** [CodeForPhilly/vacant-lots-proj#373]
**Describe the bug**
Unable to see contribution docs from README.md

**To Reproduce**
1. Go to https://github.com/CodeForPhilly/vacant-lots-proj?tab=readme-ov-file#contribution
2. Click on any link under Contribution section
3. See 404 - page not found

**Expected behavior**
Should go to the correct document for each link after clicked

**Screenshots**
![Screen Shot 2024-03-05 at 9 50 42 PM](https://github.com/CodeForPhilly/vacant-lots-proj/assets/33296817/2215cad7-dd22-4b2b-8ca4-7c5fa65cfa04)

![Screen Shot 2024-03-05 at 9 52 34 PM](https://github.com/CodeForPhilly/vacant-lots-proj/assets/33296817/57d4205e-c492-48a9-baf2-cf0281a2e2d7)

**Comment by BayLadyCoder** [comment]
Can I get assigned to fix this issue, please?

**Comment by bacitracin** [comment]
@BayLadyCoder This might be a dupe? Just FYI this issue exists https://github.com/CodeForPhilly/vacant-lots-proj/issues/360

**Comment by BayLadyCoder** [comment]
Thank you, @bacitracin! 

This issue is a little bit different than #360. It seems to come from the recent commits from last week (https://github.com/CodeForPhilly/vacant-lots-proj/commit/6488bf794e18a7d0aa005da630b22aa485186096 and https://github.com/CodeForPhilly/vacant-lots-proj/commit/e09e91f3b63583bf2c785f0ae0898576bd1c10e1) which renamed the directory from /DOCS to /docs, made all files in /docs impossible to reach through README.md. We just need to update the path in the README.md to the new one, and the fix should resolve both issues, #373 and #360. 

Feel free to assign me #360, I will fix both issues  in one PR.
