### ISSUE TITLE
BUG: React/JSX errors on /transform-property

### ISSUE THREAD

**Issue by brandonfcohen1** [CodeForPhilly/vacant-lots-proj#376]
Describe the bug
React/JSX errors on https://www.cleanandgreenphilly.org/transform-property

To Reproduce

Go to https://www.cleanandgreenphilly.org/transform-property
Open Console
Expected behavior
No Errors

**Comment by brandonfcohen1** [comment]
@liathirsh do you want to take this one as well?

**Comment by liathirsh** [comment]
@brandonfcohen1 Sure!
