### ISSUE TITLE
Usability: Fix position of Back button

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#395]
When you look at a property and scroll down the back button scrolls away as well. It focues you to scroll all the way up to get to it. 

Fix that row with the back button so users can instantly hit the back button and don't to scroll up. https://share.cleanshot.com/kB0bmnKz

You need to make sure that when you click on another property the property panel appears scrolled all the way to the top.

**Comment by paulhchoi** [comment]
@Moylena this can be set to 'in review'

**Comment by bacitracin** [comment]
@paulhchoi I think the intent for this might have been to have the entire row be sticky, not just the button (like on the find properties page) @thansidwell can you clarify?

**Comment by thansidwell** [comment]
@bacitracin @paulhchoi Yes, the whole row should be fixed or sticky, not just the button. You can see it in [this prototype](https://www.figma.com/proto/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?page-id=187%3A12602&type=design&node-id=2592-30687&viewport=-3874%2C-3906%2C0.48&t=0oJ5G6YEVKEHxswp-8&scaling=min-zoom&starting-point-node-id=2592%3A30019&hide-ui=1).

**Comment by paulhchoi** [comment]
@bacitracin thanks for the catch! @thansidwell heres the PR to make the whole bar sticky: https://github.com/CodeForPhilly/vacant-lots-proj/pull/493
