### ISSUE TITLE
Styling: Fix styling Tags in Filter

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#397]
In the filter, now the current interactive tags don't match the prototype. https://share.cleanshot.com/ZRsC77rQ

Change text size to the body-sm text style which is 14px. 

Fix the sizes, spacing and padding to to match this. https://share.cleanshot.com/g791snhc

Build these different statuses including the different background colors. https://share.cleanshot.com/YZMQ98l2

Here's a video showing how the interaction should look. https://share.cleanshot.com/wdCbXP31

**Comment by Amberroseweeks** [comment]
Hi, I'd like to assign myself this issue if it's still available.
