### ISSUE TITLE
Automate updates to Mapbox via API 

### ISSUE THREAD

**Issue by nlebovits** [CodeForPhilly/vacant-lots-proj#4]
When the dataset is finalized, updates to the Mapbox vector tile layer need to be made via API. This can happen no more frequently than once a month, given when the underlying properties dataset updates. For further info, read [documentation on the Mapbox vector tiles API](https://docs.mapbox.com/api/maps/vector-tiles/), as well as [how to update Mapbox layers via API](https://docs.mapbox.com/mapbox-tiling-service/guides/#update-a-tileset-with-mts).

**Comment by brandonfcohen1** [comment]
probably won't use GH Actions here, will determine best way

**Comment by brandonfcohen1** [comment]
not using mapbox
