### ISSUE TITLE
Task: get filters working + styled

### ISSUE THREAD

**Issue by brandonfcohen1** [CodeForPhilly/vacant-lots-proj#40]
<img width="647" alt="image" src="https://github.com/CodeForPhilly/vacant-lots-proj/assets/2308834/e299c3d8-735b-43be-84bf-0b31d0f91b69">

`multi-range-slider-react` is ugly out the box, we need to put working into making that look nicer and clean up the others

**Comment by nlebovits** [comment]
Filter styling guidance from the UX team: 
![image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/111617674/15d7fc90-fdf5-45c7-a110-64b58c40f967)

**Comment by nlebovits** [comment]
Additional update: get the filters working properly. Most important filters are: priority level, acquisition process, and geographies (neighborhood + council district for now).

**Comment by brandonfcohen1** [comment]
@JosephAni @nlebovits I will take this one, I want to do some cleanup on the backend with the filters here

**Comment by thansidwell** [comment]
Nissim, Will and I met and made some updates to the filter for version 1. We think we should pair down the filters to what seemed to be the essential filters for now. But the property details should show the full data details, but we don't need to filter by them. I updated the prototype to reflex the change. https://www.figma.com/file/NAFkgq34abW6uJ0R7PW24T/Prototype---Vacant-Properties?type=design&node-id=38%3A7718&mode=design&t=iXiro4tbMjTL27nn-1
 
<img width="675" alt="Screen Shot 2023-12-08 at 12 09 21 PM" src="https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/0b0abfb4-bc05-4303-a920-31e4508afb82">

**Comment by brandonfcohen1** [comment]
@nlebovits - a few Q's:
* Suggested Priority: you're still working on this, right?
* Property Types: which field is this?
* Acquisition Process: you're still working on this, right?
