### ISSUE TITLE
A11y: Add a title attribute to Google Street view iframe

### ISSUE THREAD

**Issue by bacitracin** [CodeForPhilly/vacant-lots-proj#400]
## Describe the task
The iframe for Google street view needs an accessible name. See image & link below for more information on fixing it.

<img width="830" alt="Screenshot 2024-03-12 at 13 26 53" src="https://github.com/CodeForPhilly/vacant-lots-proj/assets/7329799/857ab14d-aaf3-42cd-a19f-0757f86684b3">

## Acceptance Criteria
- [ ] the iframe tag will contain a descriptive title

## Additional context
* https://dequeuniversity.com/rules/axe/4.8/frame-title?application=AxeChrome

**Comment by Amberroseweeks** [comment]
Hi, I'd like to be assigned this task if it is available. Thank you!
