### ISSUE TITLE
Add "i" icon on Properties page >  map legend > next to "Priority"

### ISSUE THREAD

**Issue by Moylena** [CodeForPhilly/vacant-lots-proj#401]
See latest Figma file for details 

https://www.figma.com/proto/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?page-id=187%3A12602&type=design&node-id=2592-26899&viewport=-657%2C-623%2C0.1&t=fqZvOvLyE9qv7AAV-8&scaling=min-zoom&starting-point-node-id=2592%3A30019&hide-ui=1

**Comment by mskNeo** [comment]
I can take this on! It's just adding the icon, so only a UI update?

**Comment by Moylena** [comment]
Yes! It was missed on the last round. Please assign the ticket to yourself. We ask that folks complete the ticket within 1 week. If you can't, np just let us know and unassign yourself. Reach out with any questions.

**Comment by mskNeo** [comment]
@Moylena I don't seem to have the access to add myself as an assignee, can I be added as a collaborator?

**Comment by Moylena** [comment]
I did it for you

**Comment by mskNeo** [comment]
Thank you! @Moylena
