### ISSUE TITLE
Images: Update Home pg hero images

### ISSUE THREAD

**Issue by Moylena** [CodeForPhilly/vacant-lots-proj#407]
Pull in new images on the left and right sides. Middle image remains the same. 

See design file for details

https://www.figma.com/proto/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?page-id=187%3A12602&type=design&node-id=2592-30019&viewport=-657%2C-623%2C0.1&t=fqZvOvLyE9qv7AAV-8&scaling=min-zoom&starting-point-node-id=2592%3A30019&hide-ui=1

**Comment by thansidwell** [comment]
I think this has been done already. The images all look correct. https://www.cleanandgreenphilly.org
