### ISSUE TITLE
Content: Update Home subhead

### ISSUE THREAD

**Issue by Moylena** [CodeForPhilly/vacant-lots-proj#409]
Update subhead next to header to: 

This tool can empower community groups and organizations trying to clean and green vacant properties to reduce gun violence.

See Figma file for design details: 

https://www.figma.com/proto/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?page-id=187%3A12602&type=design&node-id=2592-30019&viewport=-657%2C-623%2C0.1&t=fqZvOvLyE9qv7AAV-8&scaling=min-zoom&starting-point-node-id=2592%3A30019&hide-ui=1

**Comment by thansidwell** [comment]
This has been done already with this ticket. https://github.com/CodeForPhilly/vacant-lots-proj/issues/338 
It's live now! https://www.cleanandgreenphilly.org
I'm archiving this ticket.

**Comment by nlebovits** [comment]
closed by #338
