### ISSUE TITLE
Images: Remove "view" icon from Find Properties Page

### ISSUE THREAD

**Issue by Moylena** [CodeForPhilly/vacant-lots-proj#412]
Remove icon from here: https://staging.cleanandgreenphilly.org/map

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/162393051/5ccc91f9-81b6-47c6-a758-bb4765155237)

Right align remaining icons (filter and download), keeping # of properties as is

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/162393051/8f8f03db-23b4-40af-b26c-4e66618ab233)

Figma file for reference:
https://www.figma.com/proto/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?page-id=187%3A12602&type=design&node-id=2592-30019&viewport=-657%2C-623%2C0.1&t=fqZvOvLyE9qv7AAV-8&scaling=min-zoom&starting-point-node-id=2592%3A30019&hide-ui=1

**Comment by CodeWritingCow** [comment]
Hello, I started working on this ticket during tonight's Code for Philly April Hack Night. @Moylena can you assign this ticket to me? Thank you!
