### ISSUE TITLE
Small: Update # of properties to show sum total number with commas

### ISSUE THREAD

**Issue by Moylena** [CodeForPhilly/vacant-lots-proj#413]
Currently map returns # of properties as (for ex) 2000

Update to reflect the values with a comma (for ex) 2,000

**Comment by paulhchoi** [comment]
sorry this should be in 'Staging', not 'Live', that was my mistake closing this ticket!

**Comment by thansidwell** [comment]
@jgaye Looks good in the pull request preview!

**Comment by nlebovits** [comment]
closed by #453
