### ISSUE TITLE
Images: Update map zoom icons

### ISSUE THREAD

**Issue by Moylena** [CodeForPhilly/vacant-lots-proj#414]
Currently shows icons for: 

Zoom in 
Zoom out
Full screen 
Find my location 

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/162393051/1b028a28-ada1-44a8-9225-462a333233d4)

---

Change to new icons in this order, still on the bottom right of the map:

Find my location
Zoom in 
Zoom out

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/162393051/07b3984e-bd83-455e-9965-c9fee651fa12)

---

Figma file for reference: 
https://www.figma.com/proto/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=2592-26899&t=sdhkPVHItWMM3Xnn-0&scaling=min-zoom&page-id=187%3A12602&starting-point-node-id=2592%3A30019

---

**Comment by amyyeung17** [comment]
I can help with this!

**Comment by bacitracin** [comment]
@amyyeung17 assigned!

**Comment by thansidwell** [comment]
This has been merged and is live in staging. Moving to "Staging."
