### ISSUE TITLE
Bug: Safari: Stop button icons from jumping

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#422]
When you hover over buttons the icon jumps up and down. It seems to be happening on all the buttons. We should stop that from happening. 

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/92f3e163-521a-4334-a666-87abf0bc66de)

Here's a video walking through it. 

https://share.cleanshot.com/wWBmkPQP

**Comment by Amberroseweeks** [comment]
@thansidwell what browser are you using to create this issue? I don't see this myself on the live or staging site. I'm using Chrome on a mac.

**Comment by thansidwell** [comment]
@Amberroseweeks Yes, I should have checked that! I see it on **Safari** on Mac. It's not an issue on Chrome, Firefox or Opera.

**Comment by Amberroseweeks** [comment]
I found a fix for this issue, can I be assigned this issue?

giving each icon type a consolidated class and including -webkit-transform: translateZ(0); can help. I tested it out and it seems to work.
