### ISSUE TITLE
Image: Add a "full screen" icon to the map detail image

### ISSUE THREAD

**Issue by Moylena** [CodeForPhilly/vacant-lots-proj#424]
Add icon to the top right corner of the property image

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/162393051/81d210d3-354f-4dcd-9a3f-9f1faa069ad7)

See Figma file for reference: 
https://www.figma.com/proto/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=2592-30687&t=sdhkPVHItWMM3Xnn-0&scaling=min-zoom&page-id=187%3A12602&starting-point-node-id=2592%3A30019

**Comment by thansidwell** [comment]
This has already been done. It's in Staging.
