### ISSUE TITLE
Content: Update Property Information table

### ISSUE THREAD

**Issue by Moylena** [CodeForPhilly/vacant-lots-proj#426]
On map detail page: 
- Remove "Parcel Type" from left hand side of table
- Add "Access Property" to left hand side table 

Separate table sections to be grouped as:
- Suggested Priority
- Gun Crime Rate
- Tree Canopy Gap

Then a separate table just below the above should show: 
- Access Properties
- Owner
- Zip Code
- RCO
- Council District
- Market Value
- Tax Delinquency 
- L&I violations

See Figma files for exact details: 
https://www.figma.com/proto/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=2592-30687&t=sdhkPVHItWMM3Xnn-0&scaling=min-zoom&page-id=187%3A12602&starting-point-node-id=2592%3A30019

**Comment by bacitracin** [comment]
A11y annotations:
![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/7329799/f9d1cb5f-794a-4306-b337-2b826010f097)

**Comment by Amberroseweeks** [comment]
@bacitracin @thansidwell I am working on this now, I working on the link to the district number and RCO. I don't see an example of where the links lead to in Figma, do we have a site we are linking too specifically? Also, are the links part of the data dynamically at all? Tagging @brandonfcohen1 for thoughts too

**Comment by thansidwell** [comment]
@Amberroseweeks @bacitracin @nlebovits Amber is asking where the links for District Number and RCO lead that appears in the [prototype](https://www.figma.com/file/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=2592%3A30687&mode=design&t=g2Lea4QFqnqFEToj-1). 

![CleanShot 2024-04-14 at 23 16 51@2x](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/49effbe3-0532-4af3-b62b-c946ea23ab22)

I didn't make those links, and I'm not sure who did. @nlebovits, is there value having them be links? Is there a user need there? Also where would we send them? The RCO and District website? Do they have them? Is that in the data? If this is extra database work perhaps it should a separate ticket? 

@Amberroseweeks Perhaps it's best you just skip this if we can't quickly work it out. We can make a need ticket to add them if it's needed. I don't want to stall all the work you've done.

**Comment by brandonfcohen1** [comment]
@nlebovits the RCO featureserver doesn't have a website contact. We could link to the contact maybe?

**Comment by Amberroseweeks** [comment]
@thansidwell I am continuing to work on this and will omit the links for now, do we want the tooltips to be included? What would be the content for that? I am assuming it would be similar to the filter view but not all definitions are there. Here is a list of tooltips that don't have text to add:

Gun Crime Rate
Tree Canopy Gap
Tax Delinquency
L&I Violations

**Comment by thansidwell** [comment]
@Amberroseweeks We should write a new ticket to add the tooltips. We haven't written it yet. That shouldn't hold you up.

**Comment by Moylena** [comment]
@thansidwell @nlebovits  I created a new ticket for the tool tip content #527  - please advise on prioritization for the competition

**Comment by nlebovits** [comment]
closed by #524
