### ISSUE TITLE
Content + Styling: Update info cards on "Get Access" Page

### ISSUE THREAD

**Issue by Moylena** [CodeForPhilly/vacant-lots-proj#429]
Create 5 "cards" for content blocks, headers, and icons for the following sections: 

[methods]
- Get agreement from owner
- Buy from owner
- Get through conservatorship
- Gain through land bank
- Do nothing

[other methods]
- Tangle tiles
- Adverse Posession
- The Side Yard Program

Please reference Figma file for exact details

https://www.figma.com/proto/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=2592-31373&t=sdhkPVHItWMM3Xnn-0&scaling=min-zoom&page-id=187%3A12602&starting-point-node-id=2592%3A30019

**Comment by bacitracin** [comment]
A11y annotations:
![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/7329799/a77de30e-b7c3-4431-8fdd-421765e91a0f)

**Comment by AZBL** [comment]
I'd like to be assigned this please.
