### ISSUE TITLE
Content + Styling: Update content and font styling "Transform a Property"

### ISSUE THREAD

**Issue by Moylena** [CodeForPhilly/vacant-lots-proj#431]
Update copy blocks and align with header / body copy styling 

Remove old copy 

This ticket does NOT include updates to the green content cards

https://www.figma.com/proto/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=2592-31488&t=sdhkPVHItWMM3Xnn-0&scaling=min-zoom&page-id=187%3A12602&starting-point-node-id=2592%3A30019

**Comment by AZBL** [comment]
I would like to be assigned this. I'd just like a little more clarification as to the specific changes this is requesting. Thank you.

**Comment by AZBL** [comment]
To be more specific about my question. Is the desired outcome of this request to have the Transform a Property page look like the linked prototype but without the green content cards? Thanks. 

@Moylena @thansidwell

**Comment by Moylena** [comment]
@AZBL  yes! apologies for the delay

**Comment by nlebovits** [comment]
closed by #510
