### ISSUE TITLE
Image: "Transform a Property" Hero Image

### ISSUE THREAD

**Issue by Moylena** [CodeForPhilly/vacant-lots-proj#432]
Pull in new hero image for the top of this page per Figma file

https://www.figma.com/proto/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=2592-31488&t=sdhkPVHItWMM3Xnn-0&scaling=min-zoom&page-id=187%3A12602&starting-point-node-id=2592%3A30019

**Comment by thansidwell** [comment]
Here's the image needed. 

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/84d72589-c0ef-45b9-9153-2b71c28a9aef)

**Comment by Amberroseweeks** [comment]
Hello, i'd like to be assigned this task if it is available.
