### ISSUE TITLE
Content + Styling: Create content cards for "Transform a Property" - Blue

### ISSUE THREAD

**Issue by Moylena** [CodeForPhilly/vacant-lots-proj#433]
Create new BLUE content + image cards under the headers:

- Get help
- Additional considerations

This ticket does NOT include the GREEN content cards

You can greek the "Jump Start" card  for now

See Figma files for hex code and keystrokes

https://www.figma.com/proto/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=2592-31488&t=sdhkPVHItWMM3Xnn-0&scaling=min-zoom&page-id=187%3A12602&starting-point-node-id=2592%3A30019

**Comment by Moylena** [comment]
@thansidwell  we need the copy for the "Get Help" > "Jump Start" card please. Will keep status as blocked and in the backlog until you give us the green light.

**Comment by thansidwell** [comment]
@Moylena Here's the content for those! https://www.figma.com/file/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=2592%3A31488&mode=design&t=L9SSczECelERYQyy-1

**Comment by AZBL** [comment]
@Moylena I just messaged you in Slack about this as well, but I actually included these cards as part of my PR for issue #431. I didn't see this as a separate ticket at the time. Just wanted to post here as well to potentially save someone some work.

**Comment by Moylena** [comment]
Thank you - updated!
