### ISSUE TITLE
Content + Styling: Revise "About" page

### ISSUE THREAD

**Issue by Moylena** [CodeForPhilly/vacant-lots-proj#443]
Current "About" page has 2 main columns. 

New design has copy blocks on left hand side with a corresponding image on the right. Below those are sections of copy that fall within 1 column. 

Pull in new copy, images, and links to follow the revised structure. Figma has the link destinations.

Design files for reference:

https://www.figma.com/proto/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=2592-31549&t=sdhkPVHItWMM3Xnn-0&scaling=min-zoom&page-id=187%3A12602&starting-point-node-id=2592%3A30019

**Comment by cozyfestiv** [comment]
I'd like to be assigned this one!
