### ISSUE TITLE
Styling + Func: Create button for "About" page

### ISSUE THREAD

**Issue by Moylena** [CodeForPhilly/vacant-lots-proj#444]
_Style_: Button should read "Learn More" and _Func_: drive to the methodology page

_Func_: Internal links should always open in same tab

Please pull directly from the Figma file: https://www.figma.com/proto/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=2592-30019&t=sdhkPVHItWMM3Xnn-0&scaling=min-zoom&page-id=187%3A12602&starting-point-node-id=2592%3A30019

**Comment by thansidwell** [comment]
@Moylena I'm confused by what this ticket is asking. I don't see a Learn More button on the Home page. There was a Learn More button but we changed it to a "Learn How" button which scrolls you down the home page content.

**Comment by JosephAni** [comment]
Hey @thansidwell @Moylena I decided to close this issue since it has been tackled and to reduce the number of issues.

**Comment by Moylena** [comment]
This was supposed to be "Learn More" - and the ticket specified the "About" page, not home. It shows on staging so aligned with closing

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/162393051/04a2969b-7567-4891-9ca8-3fe3edb1da87)
