### ISSUE TITLE
Content + Func: update "Home" page body content

### ISSUE THREAD

**Issue by Moylena** [CodeForPhilly/vacant-lots-proj#446]
_Content:_ Pull in revised body content throughout the page 

_Func:_ External link should open in a separate tab 

See Figma file: 
https://www.figma.com/proto/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=2592-30019&t=sdhkPVHItWMM3Xnn-0&scaling=min-zoom&page-id=187%3A12602&starting-point-node-id=2592%3A30019

**Comment by thansidwell** [comment]
This has been done already with this ticket. https://github.com/CodeForPhilly/vacant-lots-proj/issues/338 
It's live now! https://www.cleanandgreenphilly.org
I'm archiving this ticket.

**Comment by nlebovits** [comment]
closed by #338
