### ISSUE TITLE
Bug: Fix Map height from causing scrolling issues

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#448]
Right now the map is too tall and causes the elements to be not visible and also awkward double scrolling issue. Here's a video describing the issue. https://share.cleanshot.com/JLNwT5gh

- Make all controls of the map be always visible. Including Search, Fullscreen, My location and legend. 
- Make sure the map doesn't increase the height of the page and cause an awkward double scrolling experience. 
- Remove the footer with copyright, legal disclaimer and contact us OR put it at the bottom of the right panel.

**Comment by paulhchoi** [comment]
@Moylena this can be moved to 'in review'

@thansidwell PR opened to fix this, would love your review

**Comment by brandonfcohen1** [comment]
this should be closed right @Moylena @thansidwell ?
