### ISSUE TITLE
Usability: Switch some buttons to Primary

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#449]
There are some buttons that would use some added emphasis to encourage users to take the action we think they would likely want and we want to encourage. 

Change these buttons to the primary version of the button, colored green. 
- Learn How 
  - at the top of the home page, to encourage people to read the page
- Get Started 
  - at the bottom of the home page, to encourage people to jump into the most likely first step, finding properties
- Done 
  - when the filter panel is open, as it's the primary action 

You can see them in the prototype. https://www.figma.com/proto/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?page-id=187%3A12602&type=design&node-id=2592-30019&viewport=-1229%2C-1293%2C0.17&t=Pe1IK3jmOV7PjqHp-8&scaling=min-zoom&starting-point-node-id=2592%3A30019&hide-ui=1

**Comment by BayLadyCoder** [comment]
I can do this with my current ticket #288 (I’m converting all the buttons to use my ThemeButton)  If that’s ok with you, can I get assigned to the ticket, please?
