### ISSUE TITLE
Usability: Indicate when list is filtered

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#457]
When a user applies a filter, indicate this by switching the button to its seleted state (with a green background) and add a number indicating the number of filter criteria are being applied. 
- Make sure you're using the new buttons that I believe @amyhangin has been working on. 
- The count should be driven by the number of **_field groups_** that have something applied. https://share.cleanshot.com/tW7v66pt

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/de31dc42-906a-4a8a-9931-307f6c4185df)

**Comment by paulhchoi** [comment]
@Moylena This can be set to 'In Development'

**Comment by paulhchoi** [comment]
@Moylena This can be set to 'In Review'

**Comment by nlebovits** [comment]
closed by #491
