### ISSUE TITLE
Usability: Change filter to a toggle/disclusure experience

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#458]
Current when a user clicks "Filter" the whole right panel is swaped for the filter controls. They have to click Done to go back. This takes the user out of the context they were just in and could likely be disorienting. Make these changes to avoid that. 

- When a user clicks filter, keep the map list controls visible above so the user doesn't lose context of where they are and what they are doing. 
- When a user clicks the "Filter" button and the filter opens, change it to the selected state. When they click the Filter button again the filter should close and the button should back to its default state. 
- Change the "Done" button to a X icon without text. Clicking this will also close the filter. It's a more common way to get out of a view. 

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/6ecfd703-366e-4bff-bdce-fbee566c61d2)

**Comment by amyyeung17** [comment]
Hi! I would like to be assigned this issue :)

**Comment by amyyeung17** [comment]
Sorry, I've been a bit tied up this week! PR should be up tomorrow. It's going to be reliant on #260 though so also waiting for that to merge.

**Comment by bacitracin** [comment]
@amyyeung17 heads up looks like the PR for #260 is merged to stage now
