### ISSUE TITLE
Usability: correct the "Find Properties" title and URL

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#460]
On the "Find Properties" page

- Change the page title which appears in the tab and search engine results from "Map" to "**Find Properties**" . 
- Change the URL which appears in the browser from "map" to "**find-properties**" . 

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/c7a86dde-1d57-4bee-83b3-765d900f2e78)

**Comment by AZBL** [comment]
I would like to be assigned this please.
