### ISSUE TITLE
Usability: Adjust initial zoom and positioning of map

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#462]
Currently, when a user comes on the Find Properties page, the map is zoomed into North Philadelphia. 

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/00985636-d072-49e4-affe-1c56e985d937)

Change this so that when users come to the map they can clearly see all of the core areas of Philadelphia, Center City, North, West, and South Philadelphia. Leave out far North East Philadelphia similar to how the City Controller's website does. https://controller.phila.gov/philadelphia-audits/mapping-gun-violence

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/0dd79282-b26b-4f58-af45-133bda3c48be)

**Comment by amyyeung17** [comment]
I can work on this! I noticed that the updated map removes one of the expected behavior of PR #442: 3 at this [comment](https://github.com/CodeForPhilly/vacant-lots-proj/pull/442#issuecomment-2005564609). Might as tackle both at once.

**Comment by bacitracin** [comment]
assigned
