### ISSUE TITLE
Usability: Logo shrinks on small screens

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#477]
When the user's browser width is between 850px and 640px, looking at the Nav header, 

- the logo becomes smaller 
- the top and bottom padding becomes smaller as well.  

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/086b7596-b470-4a32-841d-18150ead8e94)

Here's a video illustrating the issue. 

https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/2fc36510-c4f4-4e70-add8-bd06cb0dd09f

On Safari in addition

- the whole website scales down on a smaller screen. 

https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/524b8d7e-b9be-4101-90df-864aef458073

Make these fixes

- Adjust the navigation breakpoint so it breaks to the mobile view of the navigation eariler. Perhaps around 850px. 
- Stop the logo or top and right padding from becoming smaller. 
- Stop the website from scaling down on small screens. Appears to only sometimes be an issue on Safari. [Something like this](https://stackoverflow.com/questions/7078663/how-do-make-a-mobile-web-page-not-shrink) might be the fix.

**Comment by amyyeung17** [comment]
This has been bugging me for a bit, I would love to fix it. :)
