### ISSUE TITLE
Attach street view images to properties

### ISSUE THREAD

**Issue by nlebovits** [CodeForPhilly/vacant-lots-proj#5]
At some point, we'll want to find a way to attach street view images to every property in the dashboard. This may be best implemented in the front end, rather than in the dataset itself, but I want us to start exploring here. Philadelphia uses [Cyclomedia](https://cyclomedia.phila.gov/) for its street view images, although these appear to be paid. Google Street View images now cost something like 7 cents/image. This isn't urgent, but I'd like us to investigate possible options for sourcing images and come up with a best approach for getting the images onto the rest of the data in the dashboard itself, whether that's while building the dataset or in the browser.

**Comment by mandyshri** [comment]
In case there is any source of web scraping option available or we can get updated images from some open dataset why not just put them in our database for the time being the only condition I see is getting the updated ones.

**Comment by brandonfcohen1** [comment]
It's just a matter of using the Streetview API- which is easy just costs a bit of money. I think we wait to see if we can get funding for the project. Maybe we can also get some credit through Google.

**Comment by nlebovits** [comment]
> It's just a matter of using the Streetview API- which is easy just costs a bit of money. I think we wait to see if we can get funding for the project. Maybe we can also get some credit through Google.

Bumping this now that we have some funding! We can build this into the budget.
