### ISSUE TITLE
Feature: Share property button

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#500]
Add a Share button with a share icon to the top of the property detail

When a user hovers over it
- a tooltip appears above the button saying "Copy Link" 

When a user clicks on it
- the tooltip changes to "Link Copied"
- the URL is copy to the user's clipboard

The user should be able to paste and send the URL to another user. 

[Figma prototype](https://www.figma.com/file/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=2592%3A30687&mode=design&t=L9SSczECelERYQyy-1)

This should use the [tooltip](https://www.figma.com/file/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=4304%3A35855&mode=design&t=TMx1kZ7ygrhbLR1X-1) component. We should ensure that whatever component we use is styled like the design.

https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/7799f802-b24c-432d-a07d-8a93fe82e2df

**Comment by Moylena** [comment]
For anyone who picks this up - please connect with @brandonfcohen1 . He's done some work to pull in data and metadata that will impact the URL for each property

**Comment by amyyeung17** [comment]
I can work on this.

**Comment by brandonfcohen1** [comment]
No metadata needed- all you need to do is copy the current URL (which will have the property ID)

**Comment by nlebovits** [comment]
closed by #533
