### ISSUE TITLE
Styling: Improve property tooltip

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#502]
Right now the current property tooltip on the map

- Blends into the map since it's white
- Doesn't match the style of the rest of the site
- The close icon is awardly placed

Change the tooltip to this styling. 

- Dark background, white text, rounded edges, new close icon, close icon far right inline with the text

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/7c752de8-e374-4e15-a729-f34c6a3a2917)

It should use the [tooltip component](https://www.figma.com/file/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=4304%3A35855&mode=design&t=EhbuNgZAuhBTthHD-1) or be styled to look like it. I have it built out with different variations. With and without a tick/tail/triangle and with and without a close icon.

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/79cf2a02-8e3d-4f43-849a-595fd0278e8f)

Here's the [prototype page](https://www.figma.com/file/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=4304%3A35573&mode=design&t=EhbuNgZAuhBTthHD-1) where the property tooltip appears.

**Comment by ajtw7** [comment]
@nlebovits assign to me.

**Comment by Moylena** [comment]
@ajtw7  assigned!

**Comment by nlebovits** [comment]
closed by #555, #562
