### ISSUE TITLE
Styling: property cards fixes

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#503]
The property cards have these issues
- Mismatched awkward border radius on porperty cards and images
- Extra spacing appears the text and badges when the page is taller. Here's a [video illustrating it](https://share.cleanshot.com/KncMQ4LM). 

Make these changes
- Outer corner radius should be 16px
- Image corners radius should be 8px 
- Padding between the description and badge 12px 

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/f0cc573d-5ff8-4590-be4a-511d3fe10d42)

[Prototype](https://www.figma.com/file/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=2592%3A26899&mode=design&t=qj4VrpdLxZfVrYle-1)

**Comment by amyyeung17** [comment]
@thansidwell @Moylena I can work on this one as well.
