### ISSUE TITLE
Usability: Add badge to details table

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#505]
On the property details table, on the Suggested Priority row

- Switch out the color swatch and text
- For colored badges 

Then it will match the badge used on proporty list cards. I'm on the fence whether is should say "High Priority" or just "High."

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/8cef68c3-9690-4f38-8b6b-d55811361b7c)

Also, please remove the 1px border that appears on all badges. 

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/6318cb46-49fe-432c-b4dd-fe3379215006)

**Comment by Amberroseweeks** [comment]
@thansidwell This is something I addressed in the Table Update task (https://github.com/orgs/CodeForPhilly/projects/3/views/1?pane=issue&itemId=56526628) I am just waiting to learn more about the data and what can be dynamically pulled in but this style will be applied to the table view. Here is a screenshot of the branch in progress 

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/61482332/d8396bf9-5184-4f9e-b875-b1bec3550306)

**Comment by thansidwell** [comment]
@Amberroseweeks Great! Thanks.

**Comment by nlebovits** [comment]
closed by #524
