### ISSUE TITLE
Usability: Add descriptions to Filters

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#506]
When a user opens the filter

-  the "Priority Level" and "Access Process" don't have any explaination of how what they are and how they are determined. 

Make these changes

- Add muted description text under each matching the prototype
- Change "Prority Level" to "Suggested Priority"
- Add "Learn More" links should link to the [Methodology](https://www.cleanandgreenphilly.org/methodology) page. Ideally scrolling down the the associated section. 
- Remove the Info icons next to the headers

[View Prototype](https://www.figma.com/file/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=2592%3A26981&mode=design&t=TMx1kZ7ygrhbLR1X-1)
 
![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/7962a5d1-0d21-4e9e-9729-2a559eb0ec4a)

**Comment by amyyeung17** [comment]
@thansidwell @Moylena I would like to work on this.
