### ISSUE TITLE
Feature: Filter by Neighborhood and Community Organizations

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#508]
Add the ability to fitler by these two fields matching the [prototype](https://www.figma.com/file/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=2592%3A26981&mode=design&t=TMx1kZ7ygrhbLR1X-1). 

- Neighborhoods
- Community Organizations

I believe the backend work has already been done and this data is in the database. 

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/12b266da-fe8e-44a1-a0a8-b7803fcfa4ca)

This should use a multi-select field component with all the appropriate state matching the [design](https://www.figma.com/file/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=3386%3A6293&mode=design&t=TMx1kZ7ygrhbLR1X-1). 

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/18e13d23-6367-4a24-bd87-7ad17416fb5e)

**Comment by jgrimes86** [comment]
Hello @Moylena.  I would like to try to resolve this issue.  Can I be assigned to it?

**Comment by thansidwell** [comment]
Thanks, @jgrimes86! I assigned you.

**Comment by nlebovits** [comment]
Thanks @jgrimes86! @paulhchoi if you can review Jim's PR when ready, that would be great

**Comment by brandonfcohen1** [comment]
Per convo with @jgrimes86 on slack, we'll need to display RCO better in the database, right now we just mash a bunch of contact info together. I'll make a new ticket for that

**Comment by brandonfcohen1** [comment]
https://github.com/CodeForPhilly/vacant-lots-proj/issues/511

**Comment by brandonfcohen1** [comment]
@jgrimes86 I added a field called `rco_names` which has names you can filter on for the RCOs. You can add to https://github.com/CodeForPhilly/vacant-lots-proj/pull/512 or create a new PR

**Comment by jgrimes86** [comment]
Thank you @brandonfcohen1.  I'm working on some requested changes to https://github.com/CodeForPhilly/vacant-lots-proj/pull/512, so I will add it there.

**Comment by nlebovits** [comment]
closed by #511, #512
