### ISSUE TITLE
Fix nav padding

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#525]
The left and right padding on the header is too much and doesn't match the prototype. 

Make it 28px on desktop and 20px on mobile. 

### On Desktop 

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/e95ad663-e188-4a01-b21e-c03436d95e85)

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/5477e632-f987-4dfb-af92-50e5afa94f99)

### On Mobile

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/19597447-6adc-4ff6-ade8-3ba6110805f2)

**Comment by amyyeung17** [comment]
I can work on this. :)
