### ISSUE TITLE
Styling: Smooth out content container resizing

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#526]
As you adjust the content container width snaps to certain breakpoints. 

- The margins can be very wide at certain breakponts and very narrow at others, appearing awkward.
- The content container is sometimes smaller than it needs to be, not filling the space optimally. 
- Resizing appears very jumping and rigid. 

https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/4c76ed1c-4f7c-45aa-b038-c43f9a3a77a3

Change the experience so that...

- The left/right margin stays consistent. 
- The content fills the avaliable space well.  
- When resizing it's much more fluid.

I messed with the CSS, taking out some classes and was able to achieve close to what I believe we need. 

https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/c564baf7-848b-45b5-a486-aa25aa4b230e

**Comment by amyyeung17** [comment]
This is related to #534. I can implement this in the layout.ts to replace all the wrapper components we currently have.

**Comment by nlebovits** [comment]
closed by #537
