### ISSUE TITLE
Add close button to download section

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#535]
When a user clicks the download button, there's no clear way to exit and get back to the list where you were. You can click the Download button again, but that's not very obvious. 

Add a X icon button to close the section and go back to the list. 

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/e3279868-122e-4d82-8ef7-3d579adeb875)

Similar to the filter section/panel

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/a66e3539-013d-4132-b8c7-d59b1716c56b)

**Comment by nlebovits** [comment]
closed by #579
