### ISSUE TITLE
Add "Download" text to button

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#536]
The download button doesn't have any text clarifying what the action is, just the icon which isn't a very reliable. 

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/f6ac6b7f-9b78-43ea-83bf-8b1c3bb1ed7a)

Add text to clarify this. We could use a tooltip, but there are enough space for this and this is better UX. 

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/fa43a1c6-9ead-4a78-b9d6-04d45870339f)

**Comment by nlebovits** [comment]
closed by #578
