### ISSUE TITLE
Swap URLs for Links

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#540]
On the Get Access there are URLS in the text. 

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/df14294c-5ef8-4be6-8f11-2f4d1bba30b6)

We should turn them into actual links users can click on and go to those websites. Like here. 

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/25d3c39b-d21c-482a-9d57-4eec59e4ad45)

These seem to be the link that need to be created. 

- Grounded in Philly
- Act 135
- The Philadelphia Land Bank
- Grounded in Philly 
- Philadelphia Legal Assistance
- Garden Justice Legal Initiative
- Land Bank’s guide to the side yard acquisition process

**Comment by thansidwell** [comment]
This is fixed on Staging, so I'm moving this to "In Staging."

**Comment by nlebovits** [comment]
closed by #564
