### ISSUE TITLE
Improve property Transform section

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#541]
On a property the Tranform section is pretty plain and uninteresting. 

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/28586013-b6f0-4d8a-8b85-ecb67ea79308)

Make it more appealing and inspirint to users by making these changes. 

- Heading changed to "Transform a Property" 
- Add a card with these new elements
  - image, content, arrow icon, heading, and description
- Clicking on this card takes users to the Transform page 

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/fe3ee516-364b-47be-a7aa-282a9b2b6485)

**Comment by Amberroseweeks** [comment]
@thansidwell can I be assigned this ticket if no one else is working on it?

**Comment by nlebovits** [comment]
closed by #543
