### ISSUE TITLE
Adjust Removing property section

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#544]
The action to remove a property now draws a lot of attention, more than it really needs to. 

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/7e4976f1-02e5-48f3-a820-80be81561ac8)

Make these changes to make it avaliable, but distract from other more important areas. [Prototype](https://www.figma.com/file/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=2592%3A30687&mode=design&t=557ZVPnALOCHgM03-1)

- Remove the heading
- Change the paragraph text
- Add "Request we hide this property" button which will link to the Request Removal page

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/a7c9edf1-e42b-444f-b143-f18b2edfcc01)

**Comment by nlebovits** [comment]
closed by #580
