### ISSUE TITLE
Gentrification Page

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#549]
On the Transform page there's a section about Gentrification. Add a link that leads to a whole page going more deeply on the topic. 

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/ff8e1422-9ca5-4255-911d-d31d09d97eb0)

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/d2d006e7-4add-43bf-acbd-d21148bb4a92)

Here's a link to the [prototype](https://www.figma.com/file/NAFkgq34abW6uJ0R7PW24T/Prototype---Clean-%26-Green-Philly?type=design&node-id=2951%3A7207&mode=design&t=8QHjMObkOywSCdKO-1) where you should be able to copy the text.

**Comment by AZBL** [comment]
I'd like to be assigned this please.

**Comment by nlebovits** [comment]
closed by #552, #553
