### ISSUE TITLE
Filter by Community Organization

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#550]
Add the ability for users to filter by Community Organization. 

The filter is already there, but it doesn't seem to work. 

https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/1d995d77-1833-49db-adde-82295a64ce98

@nlebovits Perhaps we should also add Community Organization to the property data table?

**Comment by nlebovits** [comment]
Yeah, this looks like a bug. I think it has to do with how the data are currently stored. We can revisit after launch--would take a little while to get resolved.

**Comment by brandonfcohen1** [comment]
@jgrimes86 is working on this I believe

**Comment by jgrimes86** [comment]
Working on it, but getting nowhere.  I don't think I'm going to be able to fix this.

**Comment by brandonfcohen1** [comment]
I’ll take a look tonight
