### ISSUE TITLE
Fix top padding on "Transform page"

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#560]
Currently on Staging, somehow the Transform property page has too much top padding. Reduce it from 140px to 60px that it should to match the others. 

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/6b1e44d7-4d4a-44ad-842f-3306f70847da)

Remove the extra 80px padding. It's here. 

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/bfe14fe6-5dfe-4187-aa3b-f2ed036a1396)

**Comment by thansidwell** [comment]
It looks like someone did this on Staging, so I'm moving this to "In Staging."

**Comment by nlebovits** [comment]
closed by #565
