### ISSUE TITLE
Fixing border table on map list controls

### ISSUE THREAD

**Issue by thansidwell** [CodeForPhilly/vacant-lots-proj#566]
On the map controls, when you scroll down the table border peak out from the edges. It didn't have this problem earlier. 

https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/bc01ab26-a384-41d5-8c0f-4afb49dbe97c

![Image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/d7f90bb8-ad37-4430-b362-0d49ec94b6e3)

When you scroll down the side of the table shouldn't appear next to the controls. I would think adding padding and shifting the positioning will fix it.  

https://github.com/CodeForPhilly/vacant-lots-proj/assets/1965986/6becc188-a482-4800-84c0-9d64c29d27fc

**Comment by nlebovits** [comment]
closed by #577
