### ISSUE TITLE
Bug: CSS warning on property detail

### ISSUE THREAD

**Issue by brandonfcohen1** [CodeForPhilly/vacant-lots-proj#573]
**Describe the bug**
When navigating to a property, there is a CSS warning:
```
app-index.js:35 Warning: Invalid DOM property `fill-rule`. Did you mean `fillRule`?
    at path
    at svg
    at Rake
    at div
    at div
    at Card
    at PropertyAccessOptionCard
```

**To Reproduce**
1. Go to http://localhost:3000/find-properties/452018920
2. Open console

**Expected behavior**
No errors or warnings

**Screenshots**
<img width="1508" alt="Screenshot 2024-04-21 at 7 53 06 PM" src="https://github.com/CodeForPhilly/vacant-lots-proj/assets/2308834/32694549-552b-40a3-a6bd-5342f4775bfe">

**Comment by paulhchoi** [comment]
@brandonfcohen1 great catch, i think this will be handled with the linting pr i just put up with the changes at : https://github.com/CodeForPhilly/vacant-lots-proj/pull/574/commits/7e7e5d4b0252e264316c5f8e0c0da24a9bcef6ca#diff-e91c7f6274e6da4321a7c1355140df675b7808d833dd94ec188b93fb087a0d35L10-R17. testing locally with the PR doesn't show the warning either

**Comment by brandonfcohen1** [comment]
yep, looks good on staging, will close
