### ISSUE TITLE
Blocked by client error in browser console for the Hotjar

### ISSUE THREAD

**Issue by zigouras** [CodeForPhilly/vacant-lots-proj#584]
**Describe the bug**
In the JavaScript console I see this error, both in my local build and production:
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT https://static.hotjar.com/c/hotjar-3834123.js?sv=6

**To Reproduce**
1. Go to any page in the app.
2. Click on Ctrl-shift-I to open Chrome dev tools if you are using Chrome.  Click on the console tab.

**Expected behavior**
No error.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome latest

**Additional context**
I am not exactly sure what this hotjar is used for but it looks like something for the map layout.

**Comment by brandonfcohen1** [comment]
weird, I don't see this. can you post a screenshot?

**Comment by zigouras** [comment]
![image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/16895616/874ae870-118e-4252-995e-d0e42755964f)

**Comment by zigouras** [comment]
I turned off my uBlock Origin ad blocker and the error went away.  Feel free to close this issue if you see fit.  Thanks.
