### ISSUE TITLE
Task: Show error message if map fails to load

### ISSUE THREAD

**Issue by CodeWritingCow** [CodeForPhilly/vacant-lots-proj#712]
## Describe the task
When the map fails to fetch a `pmtiles` file from Google Cloud, hide loading spinner and show an error message in `src/components/PropertyMap.tsx`

Currently, the map page shows the loading spinner spins endlessly with the message "Loading properties." This makes for a poor user experience.

## Acceptance Criteria

- [x] Hide loading spinner
- [x] Show error message instead of "Loading properties"
- [x] Show error message saying, "We are having technical issues. Please try again later."

## Additional context

* This ticket is related to #709. While working on that PR, I noticed that if the map page got a 404 error for the `pmtiles` file, it would get stuck on "Loading properties." The loader would spin endlessly.
* Here's a screenshot of what that looks like to a user:

<img width="1274" alt="Screen Shot 2024-06-25 at 11 41 15 AM" src="https://github.com/CodeForPhilly/clean-and-green-philly/assets/7751862/02b1994c-7d09-433f-8f1b-1fc9a494a76e">

**Comment by Michael-Dratch** [comment]
Can I pick up this task?
