### ISSUE TITLE
Add images to about page

### ISSUE THREAD

**Issue by nlebovits** [CodeForPhilly/vacant-lots-proj#72]
Just added some of the images to the 'public' subdirectory. Add them to the about page.

**Comment by JosephAni** [comment]
Hello @nlebovits is there a Figma design I can look at, and what images do you want added to the page?

**Comment by nlebovits** [comment]
https://www.figma.com/file/NAFkgq34abW6uJ0R7PW24T/Prototype---Vacant-Properties?type=design&node-id=38%3A9193&mode=design&t=Zk6Z0xT7hBV6ak9q-1

Images are in the `public` directory. It's the three .png files.
