### ISSUE TITLE
Get fonts, colors, and icons into app

### ISSUE THREAD

**Issue by nlebovits** [CodeForPhilly/vacant-lots-proj#77]
Our design team has given us font, colors, and icons for the project. These need to be integrated consistently throughout the app. See below.

Icons:
[Clean & Green Icons.zip](https://github.com/CodeForPhilly/vacant-lots-proj/files/13531557/Clean.Green.Icons.zip)

Colors:
![image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/111617674/6fc66646-a7fa-4e81-a2f7-56b4ec0888b9)

Fonts:
```{css-output.css}


:root {
  /* TYPE */
  --heading-l-family: "Nunito";
  --heading-l-size: 26px;
  --heading-l-size-rem: 1.625rem;
  --heading-l-weight: 700;
  --heading-l-style: normal;
  --heading-m-family: "Nunito";
  --heading-m-size: 27px;
  --heading-m-size-rem: 1.6875rem;
  --heading-m-weight: 700;
  --heading-m-style: normal;
  --heading-s-family: "Nunito";
  --heading-s-size: 18px;
  --heading-s-size-rem: 1.125rem;
  --heading-s-weight: 700;
  --heading-s-style: normal;
  --body-l-family: "Nunito";
  --body-l-size: 16px;
  --body-l-size-rem: 1rem;
  --body-l-weight: 400;
  --body-l-style: normal;
  --body-m-family: "Nunito";
  --body-m-size: 14px;
  --body-m-size-rem: 0.875rem;
  --body-m-weight: 400;
  --body-m-style: normal;
  --body-s-family: "Nunito";
  --body-s-size: 12px;
  --body-s-size-rem: 0.75rem;
  --body-s-weight: 400;
  --body-s-style: normal;
  --heading-xs-family: "Nunito";
  --heading-xs-size: 16px;
  --heading-xs-size-rem: 1rem;
  --heading-xs-weight: 700;
  --heading-xs-style: normal;
  --heading-xs-line-height: 20px;
  --heading-xs-line-height-rem: 1.25rem;
  --body-xl-family: "Nunito";
  --body-xl-size: 20px;
  --body-xl-size-rem: 1.25rem;
  --body-xl-weight: 400;
  --body-xl-style: normal;
}
```

**Comment by jepoy92** [comment]
I'd like to be assigned to this issue!

**Comment by jepoy92** [comment]
Hi, I'm having trouble creating a postgres database. Every time I enter ./psql -U postgres into the command line and am prompted to enter the password, it won't accept any input. Not sure what is causing this, would you have any advice?

**Comment by nlebovits** [comment]
What OS are you on? Have you checked the [latest docs in SETUP.md](https://github.com/CodeForPhilly/vacant-lots-proj/blob/main/SETUP.md)?

**Comment by jepoy92** [comment]
I'm on Windows 11 and yes, I'm specifically stuck at the Create a New Database section step 1

**Comment by nlebovits** [comment]
Try:

    Enter the Password Blindly: After the ./psql -U postgres command, when prompted for the password, they should type the password and press Enter, even though nothing appears on the screen. This is the standard behavior for many command-line based password prompts.

    Ensure Correct Password: They need to be sure they are entering the correct password for the postgres user. This would be the password set during the installation of PostgreSQL.

    Run as Administrator: Sometimes, running PowerShell as an administrator can resolve permission issues. Right-click on the PowerShell icon and select 'Run as Administrator', then try the process again.

    Check PostgreSQL Service: Ensure that the PostgreSQL service is running. They can check this by searching for 'Services' in Windows, opening it, and looking for PostgreSQL in the list. If it's not running, they should start it.

    Verify PostgreSQL Installation: If they continue to have issues, they should verify that PostgreSQL is installed correctly and that the path they are using in the cd command is correct for their installation.

    Check for Special Characters: If their password contains special characters, sometimes these can cause issues in command line environments. They might want to try changing the password to something simpler temporarily to test this.

**Comment by jepoy92** [comment]
I don't recall creating a password when installing postgres and have tried a variety of ways to figure out what that password might be. Do you have any further recommendations?

**Comment by nlebovits** [comment]
@jepoy92 sorry for missing your comment! I was away from my computer for a while. must have gotten buried in my email. we've switched to mapbox for most of our important data storage, so you can now work on the UX without needing to set up postgres at all. if you're still interested in contributing to front end stuff, check out our other open issues! we could use some styling help :)
