### ISSUE TITLE
Task: Style Table View

### ISSUE THREAD

**Issue by brandonfcohen1** [CodeForPhilly/vacant-lots-proj#84]
## Describe the task
Style the table view per the mockups

**Comment by thansidwell** [comment]
The property list table view doesn't seem like a high priority right now considering all the other things right now. I wrote a ticket to hide it for now. https://github.com/CodeForPhilly/vacant-lots-proj/issues/249 So let's hold all work on this.

**Comment by thansidwell** [comment]
@brandonfcohen1 I moved this back to the Backlog.

**Comment by Moylena** [comment]
@thansidwell  @nlebovits  Not clear on what the desired style was - doesn't look like there is an update to the table view of the properties (that's what I'm assuming you're referring to.) Should we close this?

**Comment by thansidwell** [comment]
@Moylena This doesn't apply anymore. I'll just archive this.
