### ISSUE TITLE
Task: Do something with Download button

### ISSUE THREAD

**Issue by brandonfcohen1** [CodeForPhilly/vacant-lots-proj#86]
## Describe the task
Up you @nlebovits what you want to do here. Would be trivial to download the geojson, but understand the pros/cons.

**Comment by nlebovits** [comment]
@brandonfcohen1 for now, I'd just like to show some kind of pop-up that tells people to email us and cleangreenphilly@gmail.com to get the data. Text could be something like:

"If you are interested in accessing the data behind this dashboard, please reach out to us at cleangreenphilly@gmail.com. Let us know who you are and why you want the data. We are happy to share the data with anyone with community-oriented interests!"
