### ISSUE TITLE
Task: When clicking on a property, pan and zoom to it on the map

### ISSUE THREAD

**Issue by brandonfcohen1** [CodeForPhilly/vacant-lots-proj#87]
## Describe the task
When clicking on a property, pan and zoom to it on the map

**Comment by willonabike** [comment]
And show corresponding property details on the right.

**Comment by markgoetz** [comment]
What's the best way for me to get the lat/long of a given property?  I need this to focus the map on that point once it's selected.

**Comment by nlebovits** [comment]
I would suggest calculating ST_PointOnSurface: https://postgis.net/docs/ST_PointOnSurface.html

**Comment by brandonfcohen1** [comment]
> I would suggest calculating ST_PointOnSurface: https://postgis.net/docs/ST_PointOnSurface.html

this won't work, because we actually don't use PostGIS hosted, I'm getting everything from mapbox

**Comment by brandonfcohen1** [comment]
@markgoetz in the click event you can get the property geometry here: https://github.com/CodeForPhilly/vacant-lots-proj/blob/abcbf37a5c78d6f324a19f59f826d1fa981e5aad/src/app/components/PropertyMap.tsx#L115-L117

From there you can use [centroid](https://www.npmjs.com/package/@turf/centroid) to get the center

happy to take this unless you want to give it a shot!

**Comment by markgoetz** [comment]
I might be misunderstanding the requirements - I thought the ask was to zoom to the property when you clicked it in the right-side menu, not on the map.  So this is specifically when you click on the map?

**Comment by brandonfcohen1** [comment]
d'oh- you're right. 

you can use the property `OPA_ID` to filter `featuresInView` to get the geometry then use it like I mentioned above

**Comment by markgoetz** [comment]
I got a TypeScript error when I tried to install that centroid library:
```
Could not find a declaration file for module '@turf/centroid'. '/Users/markgoetz/Documents/dev/webdev/codeforphilly/vacant-lots-proj/node_modules/@turf/centroid/dist/es/index.js' implicitly has an 'any' type.
  There are types at '/Users/markgoetz/Documents/dev/webdev/codeforphilly/vacant-lots-proj/node_modules/@turf/centroid/dist/js/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@turf/centroid' library may need to update its package.json or typings.
```

I'm wondering if it might make sense to find an alternative library / algorithm to do this.  I may stick with a simple average of the polygon points for now?

**Comment by brandonfcohen1** [comment]
turf is legit- I use it in production for my job. weird that installing just that module would give a ts error, but install the full package (`npm install @turf/turf`) and import `centroid`

**Comment by markgoetz** [comment]
I actually looked at [the source for the centroid operation](https://github.com/Turfjs/turf/blob/master/packages/turf-centroid/index.ts) and it looks like it's a relatively simple operation (it's actually equivalent to the average calculation I already had in place).  Is it okay if I move ahead without it?

**Comment by brandonfcohen1** [comment]
Definitely

**Comment by nlebovits** [comment]
made a small change to account for cases where there are NAs in the coordinates
