### ISSUE TITLE
Task: When clicking on a property on the map, load it in the side view

### ISSUE THREAD

**Issue by brandonfcohen1** [CodeForPhilly/vacant-lots-proj#88]
## Describe the task
When clicking on a property on the map, load it in the side view

**Comment by markgoetz** [comment]
@brandonfcohen1 Question for you - would we want to make the side view page its own URL, so that it can be deeplinked?  This would enable individual properties to be bookmarked and returned to individually.

**Comment by nlebovits** [comment]
> @brandonfcohen1 Question for you - would we want to make the side view page its own URL, so that it can be deeplinked? This would enable individual properties to be bookmarked and returned to individually.

I don't think this is a bad idea. See #103 as well. Would be great to kill two birds w one stone if possible.
