### ISSUE TITLE
Task: Clean up the "Zoom In" message

### ISSUE THREAD

**Issue by brandonfcohen1** [CodeForPhilly/vacant-lots-proj#89]
## Describe the task
Make this look nicer :) 

<img width="435" alt="image" src="https://github.com/CodeForPhilly/vacant-lots-proj/assets/2308834/810df28e-e191-45cd-bbbf-85cb7fb2dd66">

**Comment by nlebovits** [comment]
Working on interim, static solution using a pop-up for now.
