### ISSUE TITLE
Landing page not appearing

### ISSUE THREAD

**Issue by nlebovits** [CodeForPhilly/vacant-lots-proj#90]
The landing page doesn't show up in the deployed app. Whether opening the default link for the app or clicking the "home" button, only the map view is visible.

https://vacant-lots-proj.vercel.app/ displays:

![Screenshot 2023-12-04 at 09-02-39 Clean Green Philly](https://github.com/CodeForPhilly/vacant-lots-proj/assets/111617674/de0e7c17-1da9-4152-bd39-c1d73b7388dc)

but it should display something like:

![User prototype landing page](https://github.com/CodeForPhilly/vacant-lots-proj/assets/111617674/0776acde-9fe0-42a5-b8ab-6680525a31d7)

I'm using Firefox 120.0.01 on a Windows machine.

**Comment by brandonfcohen1** [comment]
> @brandonfcohen1 An easy issue but probably something we should address ASAP. Lmk if you have bandwidth--I can take a crack if need be.

ah, my fault. I'll fix

**Comment by nlebovits** [comment]
@all-contributors please credit @brandonfcohen1 for code

**Comment by nlebovits** [comment]
@all-contributors please add @brandonfcohen1 for code, doc, infra,
