### ISSUE TITLE
menu bar icons get small on narrow screens

### ISSUE THREAD

**Issue by brandonfcohen1** [CodeForPhilly/vacant-lots-proj#94]
![image](https://github.com/CodeForPhilly/vacant-lots-proj/assets/2308834/13e4b510-6a80-4abf-9440-a513ff94e6ef)

keep icon size consistent regardless of screen width

**Comment by jroper-scottlogic** [comment]
HI, I made a pr to hopefully fix this here
https://github.com/CodeForPhilly/vacant-lots-proj/pull/95
